Repository opensearch-project/opensearch-spark, pull requests merged in 2023-11, with the labels that each got.

#119 Add recover index job statement
  docs/index.md
  flint-core/src/main/scala/org/opensearch/flint/core/metadata/log/FlintMetadataLogEntry.scala
  flint-spark-integration/src/main/antlr4/FlintSparkSqlExtensions.g4
  flint-spark-integration/src/main/antlr4/SparkSqlBase.g4
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/FlintSpark.scala
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/sql/FlintSparkSqlAstBuilder.scala
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/sql/job/FlintSparkIndexJobAstBuilder.scala
  integ-test/src/test/scala/org/opensearch/flint/OpenSearchTransactionSuite.scala
  integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkIndexJobITSuite.scala
  integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkIndexJobSqlITSuite.scala
Labels: enhancement

#136 Bug fix, handle close scroll exception
  docs/index.md
  flint-core/src/main/scala/org/opensearch/flint/core/FlintOptions.java
  flint-core/src/main/scala/org/opensearch/flint/core/storage/OpenSearchScrollReader.java
Labels: 0.1.1

#125 Add more info in Flint metadata log
  flint-core/src/main/scala/org/opensearch/flint/core/metadata/log/DefaultOptimisticTransaction.java
  flint-core/src/main/scala/org/opensearch/flint/core/metadata/log/FlintMetadataLogEntry.scala
  flint-core/src/main/scala/org/opensearch/flint/core/storage/FlintOpenSearchMetadataLog.java
  flint-spark-integration/src/main/scala/org/apache/spark/sql/flint/package.scala
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/FlintSpark.scala
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/FlintSparkIndex.scala
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/FlintSparkIndexMonitor.scala
  integ-test/src/test/scala/org/opensearch/flint/OpenSearchTransactionSuite.scala
  integ-test/src/test/scala/org/opensearch/flint/core/FlintTransactionITSuite.scala
  integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkIndexJobITSuite.scala
  integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkSuite.scala
  integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkTransactionITSuite.scala
Labels: bug, enhancement

#127 Fix Flint index name and MV name bug
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/FlintSparkIndex.scala
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/covering/FlintSparkCoveringIndex.scala
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/mv/FlintSparkMaterializedView.scala
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/skipping/FlintSparkSkippingIndex.scala
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/sql/mv/FlintSparkMaterializedViewAstBuilder.scala
  flint-spark-integration/src/test/scala/org/opensearch/flint/spark/covering/FlintSparkCoveringIndexSuite.scala
  flint-spark-integration/src/test/scala/org/opensearch/flint/spark/mv/FlintSparkMaterializedViewSuite.scala
  flint-spark-integration/src/test/scala/org/opensearch/flint/spark/skipping/FlintSparkSkippingIndexSuite.scala
  integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkMaterializedViewSqlITSuite.scala
Labels: bug

#142 Revert EMR info in Flint metadata
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/FlintSparkIndex.scala
Labels: bug

#154 query rewrite for LogsTable skipping index
  build.sbt
  flint-spark-integration/lib/LogsConnectorSpark-1.0.jar
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/skipping/ApplyFlintSparkSkippingIndex.scala
Labels: enhancement

#158 Improve Flint index monitor error handling
  flint-spark-integration/src/main/scala/org/apache/spark/sql/flint/package.scala
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/FlintSparkIndexMonitor.scala
  integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkIndexMonitorITSuite.scala
Labels: enhancement

#169 Request index not exist handling
  flint-core/src/main/scala/org/opensearch/flint/core/FlintClient.java
  flint-core/src/main/scala/org/opensearch/flint/core/metadata/log/FlintMetadataLogEntry.scala
  flint-core/src/main/scala/org/opensearch/flint/core/storage/FlintOpenSearchClient.java
  flint-core/src/main/scala/org/opensearch/flint/core/storage/FlintOpenSearchMetadataLog.java
  flint-core/src/main/scala/org/opensearch/flint/core/storage/OpenSearchUpdater.java
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/FlintSpark.scala
  integ-test/src/test/scala/org/opensearch/flint/OpenSearchTransactionSuite.scala
  integ-test/src/test/scala/org/opensearch/flint/core/FlintOpenSearchClientSuite.scala
  integ-test/src/test/scala/org/opensearch/flint/core/FlintTransactionITSuite.scala
  integ-test/src/test/scala/org/opensearch/flint/core/OpenSearchUpdaterSuite.scala
  integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkIndexJobITSuite.scala
  integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkTransactionITSuite.scala
  spark-sql-application/src/main/scala/org/apache/spark/sql/FlintREPL.scala
Labels: enhancement, 0.1.1

#173 CloudWatch Metrics Sink Addition
  build.sbt
  flint-core/src/main/java/org/apache/spark/metrics/sink/CloudWatchSink.java
  flint-core/src/main/java/org/opensearch/flint/core/metrics/reporter/DimensionedCloudWatchReporter.java
  flint-core/src/main/java/org/opensearch/flint/core/metrics/reporter/InvalidMetricsPropertyException.java
  flint-core/src/test/java/apache/spark/metrics/sink/CloudWatchSinkTests.java
  flint-core/src/test/java/opensearch/flint/core/metrics/reporter/DimensionedCloudWatchReporterTest.java
  project/plugins.sbt
Labels: enhancement

#174 Migrate resutIndex and requestIndex state inconsistency issue
  spark-sql-application/src/main/scala/org/apache/spark/sql/FlintREPL.scala
Labels: enhancement

#170 Add backoff retry capability in rest client
  build.sbt
  docs/index.md
  flint-core/src/main/scala/org/opensearch/flint/core/FlintOptions.java
  flint-core/src/main/scala/org/opensearch/flint/core/http/FlintRetryOptions.java
  flint-core/src/main/scala/org/opensearch/flint/core/http/RetryableHttpAsyncClient.java
  flint-core/src/main/scala/org/opensearch/flint/core/http/handler/ErrorStacktraceFailurePredicate.java
  flint-core/src/main/scala/org/opensearch/flint/core/http/handler/ExceptionClassNameFailurePredicate.java
  flint-core/src/main/scala/org/opensearch/flint/core/http/handler/HttpStatusCodeResultPredicate.java
  flint-core/src/main/scala/org/opensearch/flint/core/storage/FlintOpenSearchClient.java
  flint-core/src/test/scala/org/opensearch/flint/core/http/RetryableHttpAsyncClientSuite.scala
  flint-spark-integration/src/main/scala/org/apache/spark/sql/flint/config/FlintSparkConf.scala
  flint-spark-integration/src/test/scala/org/apache/spark/sql/flint/config/FlintSparkConfSuite.scala
Labels: enhancement

#176 Add dimensions to cloudwatch metric and metric filter option for CWSink.
  build.sbt
  flint-core/src/main/java/org/apache/spark/metrics/sink/CloudWatchSink.java
  flint-core/src/main/java/org/opensearch/flint/core/metrics/reporter/DimensionedCloudWatchReporter.java
  flint-core/src/main/java/org/opensearch/flint/core/metrics/reporter/DimensionedName.java
  flint-core/src/main/java/org/opensearch/flint/core/metrics/reporter/DimensionedNameBuilder.java
  flint-core/src/test/java/opensearch/flint/core/metrics/reporter/DimensionedCloudWatchReporterTest.java
  flint-core/src/test/java/opensearch/flint/core/metrics/reporter/DimensionedNameTest.java
Labels: enhancement
