Repository opensearch-project/opensearch-spark, pull requests merged in 2024-03, with the labels that each got.

#266 Add sql grammar support for show flint index statement
  flint-spark-integration/src/main/antlr4/FlintSparkSqlExtensions.g4
  flint-spark-integration/src/main/antlr4/SparkSqlBase.g4
Labels: enhancement, 0.3

#248 Implement BloomFilter query rewrite (without pushdown optimization)
  docs/index.md
  flint-core/src/main/java/org/opensearch/flint/core/field/bloomfilter/classic/ClassicBloomFilter.java
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/skipping/bloomfilter/BloomFilterMightContain.scala
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/skipping/bloomfilter/BloomFilterSkippingStrategy.scala
  flint-spark-integration/src/test/scala/org/opensearch/flint/spark/skipping/bloomfilter/BloomFilterMightContainSuite.scala
  integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkSkippingIndexITSuite.scala
Labels: enhancement, 0.3

#271 Implement BloomFilter query pushdown optimization
  flint-spark-integration/src/main/resources/bloom_filter_query.script
  flint-spark-integration/src/main/scala/org/apache/spark/sql/flint/datatype/FlintDataType.scala
  flint-spark-integration/src/main/scala/org/apache/spark/sql/flint/storage/FlintQueryCompiler.scala
  flint-spark-integration/src/test/scala/org/apache/spark/sql/flint/datatype/FlintDataTypeSuite.scala
  flint-spark-integration/src/test/scala/org/apache/spark/sql/flint/storage/FlintQueryCompilerSuite.scala
  integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkSkippingIndexITSuite.scala
Labels: enhancement, 0.3

#279 Add grammar files for alter index
  flint-spark-integration/src/main/antlr4/FlintSparkSqlExtensions.g4
  flint-spark-integration/src/main/antlr4/SparkSqlBase.g4
Labels: enhancement, 0.3

#251 Implement adaptive BloomFilter algorithm
  flint-core/src/main/java/org/opensearch/flint/core/field/bloomfilter/BloomFilterFactory.java
  flint-core/src/main/java/org/opensearch/flint/core/field/bloomfilter/adaptive/AdaptiveBloomFilter.java
  flint-core/src/test/java/org/opensearch/flint/core/field/bloomfilter/BloomFilterFactoryTest.java
  flint-core/src/test/java/org/opensearch/flint/core/field/bloomfilter/adaptive/AdaptiveBloomFilterTest.java
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/skipping/bloomfilter/BloomFilterAgg.scala
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/skipping/bloomfilter/BloomFilterSkippingStrategy.scala
  flint-spark-integration/src/test/scala/org/opensearch/flint/spark/skipping/bloomfilter/BloomFilterSkippingStrategySuite.scala
  integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkSkippingIndexITSuite.scala
Labels: enhancement, 0.3

#274 Move query from entry point to SparkConf
  flint-spark-integration/src/main/scala/org/apache/spark/sql/flint/config/FlintSparkConf.scala
  integ-test/src/test/scala/org/apache/spark/sql/FlintREPLITSuite.scala
  spark-sql-application/src/main/scala/org/apache/spark/sql/FlintJob.scala
  spark-sql-application/src/main/scala/org/apache/spark/sql/FlintREPL.scala
  spark-sql-application/src/test/scala/org/apache/spark/sql/FlintREPLTest.scala
Labels: enhancement, 0.3

#282 Fix spark extension path in README.
  README.md
  docs/PPL-on-Spark.md
Labels: documentation

#276 Implement show flint index statement
  docs/index.md
  flint-core/src/main/scala/org/opensearch/flint/core/FlintOptions.java
  flint-core/src/main/scala/org/opensearch/flint/core/metadata/FlintMetadata.scala
  flint-core/src/main/scala/org/opensearch/flint/core/storage/FlintOpenSearchClient.java
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/FlintSparkIndex.scala
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/FlintSparkIndexFactory.scala
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/covering/FlintSparkCoveringIndex.scala
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/mv/FlintSparkMaterializedView.scala
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/skipping/FlintSparkSkippingIndex.scala
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/sql/FlintSparkSqlAstBuilder.scala
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/sql/index/FlintSparkIndexAstBuilder.scala
  integ-test/src/test/scala/org/opensearch/flint/OpenSearchTransactionSuite.scala
  integ-test/src/test/scala/org/opensearch/flint/core/FlintTransactionITSuite.scala
  integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkCoveringIndexITSuite.scala
  integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkIndexSqlITSuite.scala
  integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkMaterializedViewITSuite.scala
  integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkSkippingIndexITSuite.scala
Labels: enhancement, 0.3

#283 Add BloomFilter skipping index SQL support
  docs/index.md
  flint-spark-integration/src/main/antlr4/FlintSparkSqlExtensions.g4
  flint-spark-integration/src/main/antlr4/SparkSqlBase.g4
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/sql/skipping/FlintSparkSkippingIndexAstBuilder.scala
  integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkSkippingIndexSqlITSuite.scala
Labels: enhancement, 0.3

#284 Implement analyze skipping index statement
  docs/index.md
  flint-spark-integration/src/main/antlr4/FlintSparkSqlExtensions.g4
  flint-spark-integration/src/main/antlr4/SparkSqlBase.g4
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/FlintSpark.scala
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/skipping/recommendations/AnalyzeSkippingStrategy.scala
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/skipping/recommendations/DataTypeSkippingStrategy.scala
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/sql/skipping/FlintSparkSkippingIndexAstBuilder.scala
  integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkSkippingIndexSqlITSuite.scala
Labels: enhancement, 0.3

#287 Reduce default inactivity limit to 3min
  flint-core/src/main/scala/org/opensearch/flint/core/FlintOptions.java
Labels: 0.3

#292 Fix shutdown bug due to non-daemon thread in driver
  integ-test/src/test/scala/org/apache/spark/sql/FlintJobITSuite.scala
  spark-sql-application/src/main/scala/org/apache/spark/sql/FlintJobExecutor.scala
  spark-sql-application/src/main/scala/org/apache/spark/sql/FlintREPL.scala
  spark-sql-application/src/main/scala/org/apache/spark/sql/JobOperator.scala
Labels: bug, 0.3

#289 Rule out logical deleted skipping index in query rewrite
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/skipping/ApplyFlintSparkSkippingIndex.scala
  flint-spark-integration/src/test/scala/org/opensearch/flint/spark/skipping/ApplyFlintSparkSkippingIndexSuite.scala
  integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkSkippingIndexITSuite.scala
Labels: enhancement, 0.3

#296 Ignore non-Flint index in show and describe index statement
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/FlintSpark.scala
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/FlintSparkIndexFactory.scala
  integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkIndexSqlITSuite.scala
Labels: bug, 0.3
