Repository opensearch-project/opensearch-spark, pull requests merged in 2024-08, with the labels that each got.

#504 Support more PPL builtin functions by adding a name mapping
  integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkSuite.scala
  integ-test/src/test/scala/org/opensearch/flint/spark/ppl/FlintSparkPPLBuiltinFunctionITSuite.scala
  ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/utils/BuiltinFunctionTranslator.java
  ppl-spark-integration/src/test/scala/org/opensearch/flint/spark/ppl/PPLLogicalPlanAggregationQueriesTranslatorTestSuite.scala
  ppl-spark-integration/src/test/scala/org/opensearch/flint/spark/ppl/PPLLogicalPlanBasicQueriesTranslatorTestSuite.scala
  ppl-spark-integration/src/test/scala/org/opensearch/flint/spark/ppl/PPLLogicalPlanFiltersTranslatorTestSuite.scala
  ppl-spark-integration/src/test/scala/org/opensearch/flint/spark/ppl/PPLLogicalPlanMathFunctionsTranslatorTestSuite.scala
  ppl-spark-integration/src/test/scala/org/opensearch/flint/spark/ppl/PPLLogicalPlanStringFunctionsTranslatorTestSuite.scala
  ppl-spark-integration/src/test/scala/org/opensearch/flint/spark/ppl/PPLLogicalPlanTimeFunctionsTranslatorTestSuite.scala
Labels: bug, 0.5

#479 Add OpenSearchTable in flint core
  docs/index.md
  flint-core/src/main/java/org/opensearch/flint/core/IRestHighLevelClient.java
  flint-core/src/main/java/org/opensearch/flint/core/RestHighLevelClientWrapper.java
  flint-core/src/main/scala/org/opensearch/flint/core/FlintClient.java
  flint-core/src/main/scala/org/opensearch/flint/core/FlintOptions.java
  flint-core/src/main/scala/org/opensearch/flint/core/JsonSchema.scala
  flint-core/src/main/scala/org/opensearch/flint/core/MetaData.scala
  flint-core/src/main/scala/org/opensearch/flint/core/Schema.scala
  flint-core/src/main/scala/org/opensearch/flint/core/Table.scala
  flint-core/src/main/scala/org/opensearch/flint/core/http/FlintRetryOptions.java
  flint-core/src/main/scala/org/opensearch/flint/core/metadata/FlintMetadata.scala
  flint-core/src/main/scala/org/opensearch/flint/core/storage/FlintOpenSearchClient.java
  flint-core/src/main/scala/org/opensearch/flint/core/storage/OpenSearchReader.java
  flint-core/src/main/scala/org/opensearch/flint/core/storage/OpenSearchScrollReader.java
  flint-core/src/main/scala/org/opensearch/flint/core/storage/OpenSearchSearchAfterQueryReader.java
  flint-core/src/main/scala/org/opensearch/flint/core/table/OpenSearchIndexShardTable.scala
  flint-core/src/main/scala/org/opensearch/flint/core/table/OpenSearchIndexTable.scala
  flint-core/src/test/scala/org/opensearch/flint/core/metadata/FlintMetadataSuite.scala
  flint-core/src/test/scala/org/opensearch/flint/core/table/OpenSearchIndexTableSpec.scala
  flint-spark-integration/src/main/scala/org/apache/spark/opensearch/table/OpenSearchTable.scala
  flint-spark-integration/src/main/scala/org/apache/spark/opensearch/table/PartitionInfo.scala
  flint-spark-integration/src/main/scala/org/apache/spark/opensearch/table/ShardInfo.scala
  flint-spark-integration/src/main/scala/org/apache/spark/sql/flint/FlintPartitionReaderFactory.scala
  flint-spark-integration/src/main/scala/org/apache/spark/sql/flint/FlintReadOnlyTable.scala
  flint-spark-integration/src/main/scala/org/apache/spark/sql/flint/FlintScan.scala
  flint-spark-integration/src/main/scala/org/apache/spark/sql/flint/FlintScanBuilder.scala
  flint-spark-integration/src/main/scala/org/apache/spark/sql/flint/config/FlintSparkConf.scala
  flint-spark-integration/src/test/scala/org/apache/spark/sql/flint/config/FlintSparkConfSuite.scala
  flint-spark-integration/src/test/scala/org/opensearch/flint/spark/covering/ApplyFlintSparkCoveringIndexSuite.scala
  integ-test/src/test/scala/org/opensearch/flint/OpenSearchSuite.scala
  integ-test/src/test/scala/org/opensearch/flint/core/FlintOpenSearchClientSuite.scala
  spark-sql-application/src/main/scala/org/apache/spark/sql/OSClient.scala
Labels: 0.5

#501 Reorganize IT directory to prevent unintentional execution from UT
  .github/workflows/test-and-build-workflow.yml
  DEVELOPER_GUIDE.md
  build.sbt
  integ-test/src/aws-integration/scala/org/opensearch/flint/core/aws/AWSOpenSearchAccessTestSuite.scala
  integ-test/src/aws-integration/scala/org/opensearch/flint/core/aws/AWSOpenSearchSuite.scala
  integ-test/src/aws-integration/scala/org/opensearch/flint/spark/aws/AWSEmrServerlessAccessTestSuite.scala
  integ-test/src/integration/java/org/opensearch/testcontainers/OpenSearchContainer.java
  integ-test/src/integration/scala/org/apache/spark/FlintDataSourceV2ITSuite.scala
  integ-test/src/integration/scala/org/apache/spark/opensearch/catalog/OpenSearchCatalogITSuite.scala
  integ-test/src/integration/scala/org/apache/spark/opensearch/table/OpenSearchCatalogSuite.scala
  integ-test/src/integration/scala/org/apache/spark/opensearch/table/OpenSearchTableITSuite.scala
  integ-test/src/integration/scala/org/apache/spark/sql/FlintJobITSuite.scala
  integ-test/src/integration/scala/org/apache/spark/sql/FlintREPLITSuite.scala
  integ-test/src/integration/scala/org/apache/spark/sql/JobTest.scala
  integ-test/src/integration/scala/org/apache/spark/sql/REPLResult.scala
  integ-test/src/integration/scala/org/apache/spark/sql/SparkHiveSupportSuite.scala
  integ-test/src/integration/scala/org/opensearch/flint/OpenSearchSuite.scala
  integ-test/src/integration/scala/org/opensearch/flint/OpenSearchTransactionSuite.scala
  integ-test/src/integration/scala/org/opensearch/flint/core/FlintMetadataLogITSuite.scala
  integ-test/src/integration/scala/org/opensearch/flint/core/FlintOpenSearchClientSuite.scala
  integ-test/src/integration/scala/org/opensearch/flint/core/FlintTransactionITSuite.scala
  integ-test/src/integration/scala/org/opensearch/flint/core/OpenSearchUpdaterSuite.scala
  integ-test/src/integration/scala/org/opensearch/flint/spark/FlintSparkCoveringIndexITSuite.scala
  integ-test/src/integration/scala/org/opensearch/flint/spark/FlintSparkCoveringIndexSqlITSuite.scala
  integ-test/src/integration/scala/org/opensearch/flint/spark/FlintSparkIndexJobITSuite.scala
  integ-test/src/integration/scala/org/opensearch/flint/spark/FlintSparkIndexJobSqlITSuite.scala
  integ-test/src/integration/scala/org/opensearch/flint/spark/FlintSparkIndexMonitorITSuite.scala
  integ-test/src/integration/scala/org/opensearch/flint/spark/FlintSparkIndexNameITSuite.scala
  integ-test/src/integration/scala/org/opensearch/flint/spark/FlintSparkIndexSqlITSuite.scala
  integ-test/src/integration/scala/org/opensearch/flint/spark/FlintSparkIndexValidationITSuite.scala
  integ-test/src/integration/scala/org/opensearch/flint/spark/FlintSparkMaterializedViewITSuite.scala
  integ-test/src/integration/scala/org/opensearch/flint/spark/FlintSparkMaterializedViewSqlITSuite.scala
  integ-test/src/integration/scala/org/opensearch/flint/spark/FlintSparkSkippingIndexITSuite.scala
  integ-test/src/integration/scala/org/opensearch/flint/spark/FlintSparkSkippingIndexSqlITSuite.scala
  integ-test/src/integration/scala/org/opensearch/flint/spark/FlintSparkSuite.scala
  integ-test/src/integration/scala/org/opensearch/flint/spark/FlintSparkTransactionITSuite.scala
  integ-test/src/integration/scala/org/opensearch/flint/spark/FlintSparkUpdateIndexITSuite.scala
  integ-test/src/integration/scala/org/opensearch/flint/spark/FlintSparkWindowingFunctionITSuite.scala
  integ-test/src/integration/scala/org/opensearch/flint/spark/LogicalPlanTestUtils.scala
  integ-test/src/integration/scala/org/opensearch/flint/spark/iceberg/FlintSparkIcebergCoveringIndexITSuite.scala
  integ-test/src/integration/scala/org/opensearch/flint/spark/iceberg/FlintSparkIcebergMaterializedViewITSuite.scala
  integ-test/src/integration/scala/org/opensearch/flint/spark/iceberg/FlintSparkIcebergSkippingIndexITSuite.scala
  integ-test/src/integration/scala/org/opensearch/flint/spark/iceberg/FlintSparkIcebergSuite.scala
  integ-test/src/integration/scala/org/opensearch/flint/spark/ppl/FlintPPLSuite.scala
  integ-test/src/integration/scala/org/opensearch/flint/spark/ppl/FlintSparkPPLAggregationWithSpanITSuite.scala
  integ-test/src/integration/scala/org/opensearch/flint/spark/ppl/FlintSparkPPLAggregationsITSuite.scala
  integ-test/src/integration/scala/org/opensearch/flint/spark/ppl/FlintSparkPPLBasicITSuite.scala
  integ-test/src/integration/scala/org/opensearch/flint/spark/ppl/FlintSparkPPLBuiltinFunctionITSuite.scala
  integ-test/src/integration/scala/org/opensearch/flint/spark/ppl/FlintSparkPPLCorrelationITSuite.scala
  integ-test/src/integration/scala/org/opensearch/flint/spark/ppl/FlintSparkPPLEvalITSuite.scala
  integ-test/src/integration/scala/org/opensearch/flint/spark/ppl/FlintSparkPPLFiltersITSuite.scala
  integ-test/src/integration/scala/org/opensearch/flint/spark/ppl/FlintSparkPPLTimeWindowITSuite.scala
Labels: infrastructure, 0.5

#411 Add config on query loop execution frequency
  integ-test/src/integration/scala/org/apache/spark/sql/FlintREPLITSuite.scala
  spark-sql-application/src/main/scala/org/apache/spark/sql/CommandContext.scala
  spark-sql-application/src/main/scala/org/apache/spark/sql/FlintREPL.scala
  spark-sql-application/src/test/scala/org/apache/spark/sql/FlintREPLTest.scala
Labels: enhancement, 0.5

#500 Terminate streaming job when index data is deleted
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/FlintSpark.scala
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/FlintSparkIndexMonitor.scala
  integ-test/src/integration/scala/org/opensearch/flint/spark/FlintSparkIndexMonitorITSuite.scala
  integ-test/src/integration/scala/org/opensearch/flint/spark/FlintSparkSuite.scala
Labels: bug, 0.5

#525 Upgrade Spark 3.5.1
  README.md
  build.sbt
  flint-core/src/main/java/org/opensearch/flint/core/metrics/reporter/DimensionUtils.java
  flint-core/src/main/java/org/opensearch/flint/core/metrics/reporter/DimensionedCloudWatchReporter.java
  flint-spark-integration/src/main/scala/org/apache/spark/sql/flint/FlintScan.scala
  flint-spark-integration/src/main/scala/org/apache/spark/sql/flint/FlintScanBuilder.scala
  flint-spark-integration/src/main/scala/org/apache/spark/sql/flint/FlintWrite.scala
  flint-spark-integration/src/main/scala/org/apache/spark/sql/flint/json/FlintJacksonParser.scala
  flint-spark-integration/src/main/scala/org/apache/spark/sql/flint/package.scala
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/skipping/FlintSparkSkippingFileIndex.scala
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/skipping/FlintSparkSkippingStrategy.scala
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/skipping/bloomfilter/BloomFilterMightContain.scala
  flint-spark-integration/src/test/scala/org/apache/spark/sql/FlintCatalogSuite.scala
  flint-spark-integration/src/test/scala/org/opensearch/flint/spark/covering/ApplyFlintSparkCoveringIndexSuite.scala
  flint-spark-integration/src/test/scala/org/opensearch/flint/spark/skipping/ApplyFlintSparkSkippingIndexSuite.scala
  flint-spark-integration/src/test/scala/org/opensearch/flint/spark/skipping/FlintSparkSkippingFileIndexSuite.scala
  integ-test/src/integration/scala/org/apache/spark/FlintDataSourceV2ITSuite.scala
  integ-test/src/integration/scala/org/apache/spark/opensearch/catalog/OpenSearchCatalogITSuite.scala
  integ-test/src/integration/scala/org/apache/spark/opensearch/table/OpenSearchCatalogSuite.scala
  integ-test/src/integration/scala/org/opensearch/flint/spark/FlintSparkMaterializedViewSqlITSuite.scala
  integ-test/src/integration/scala/org/opensearch/flint/spark/FlintSparkSkippingIndexSqlITSuite.scala
  integ-test/src/integration/scala/org/opensearch/flint/spark/FlintSparkSuite.scala
  integ-test/src/integration/scala/org/opensearch/flint/spark/FlintSparkWindowingFunctionITSuite.scala
  integ-test/src/integration/scala/org/opensearch/flint/spark/iceberg/FlintSparkIcebergSuite.scala
  integ-test/src/integration/scala/org/opensearch/flint/spark/ppl/FlintSparkPPLEvalITSuite.scala
  integ-test/src/integration/scala/org/opensearch/flint/spark/sessioncatalog/FlintSessionCatalogSuite.scala
  integ-test/src/integration/scala/org/opensearch/flint/spark/sessioncatalog/FlintSparkSessionCatalogMaterializedViewITSuite.scala
  integ-test/src/integration/scala/org/opensearch/flint/spark/sessioncatalog/FlintSparkSessionCatalogSkippingIndexITSuite.scala
  spark-sql-application/src/test/scala/org/opensearch/sql/FlintDelegatingSessionCatalogTest.scala
Labels: 0.5

#546 Some fixes for the README
  README.md
Labels: documentation, 0.6

#539 Add statement timeout
  flint-commons/src/main/scala/org/opensearch/flint/common/model/ContextualDataStore.scala
  flint-commons/src/main/scala/org/opensearch/flint/common/model/FlintStatement.scala
  flint-commons/src/main/scala/org/opensearch/flint/common/model/InteractiveSession.scala
  flint-commons/src/test/scala/org/opensearch/flint/common/model/InteractiveSessionTest.scala
  integ-test/src/integration/scala/org/apache/spark/sql/FlintREPLITSuite.scala
  integ-test/src/integration/scala/org/opensearch/flint/core/OpenSearchUpdaterSuite.scala
  spark-sql-application/src/main/scala/org/apache/spark/sql/FlintJobExecutor.scala
  spark-sql-application/src/main/scala/org/apache/spark/sql/FlintREPL.scala
  spark-sql-application/src/main/scala/org/apache/spark/sql/JobOperator.scala
  spark-sql-application/src/test/scala/org/apache/spark/sql/FlintREPLTest.scala
Labels: 0.6, backport 0.5

#552 Remove query rewrite for LogsTable skipping index
  build.sbt
  flint-spark-integration/lib/LogsConnectorSpark-1.0.jar
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/skipping/ApplyFlintSparkSkippingIndex.scala
Labels: maintenance, 0.6, backport 0.5

#554 Fix refresh policy back to WAIT_FOR other than writing query result
  flint-core/src/main/scala/org/opensearch/flint/core/storage/FlintOpenSearchMetadataLog.java
  flint-core/src/main/scala/org/opensearch/flint/core/storage/OpenSearchUpdater.java
  integ-test/src/integration/scala/org/apache/spark/sql/FlintREPLITSuite.scala
  integ-test/src/integration/scala/org/opensearch/flint/core/OpenSearchUpdaterSuite.scala
  spark-sql-application/src/main/scala/org/apache/spark/sql/OSClient.scala
Labels: backport 0.5

#544 Lateral `eval` expressions are supported after Spark upgrading
  integ-test/src/integration/scala/org/opensearch/flint/spark/ppl/FlintSparkPPLEvalITSuite.scala
  ppl-spark-integration/README.md
Labels: enhancement, 0.6, backport 0.5

#567 Add rate limiter for bulk request
  docs/index.md
  flint-core/src/main/java/org/opensearch/flint/core/RestHighLevelClientWrapper.java
  flint-core/src/main/scala/org/opensearch/flint/core/FlintOptions.java
  flint-core/src/main/scala/org/opensearch/flint/core/storage/BulkRequestRateLimiter.java
  flint-core/src/main/scala/org/opensearch/flint/core/storage/BulkRequestRateLimiterHolder.java
  flint-core/src/main/scala/org/opensearch/flint/core/storage/OpenSearchClientUtils.java
  flint-core/src/test/scala/org/opensearch/flint/core/storage/BulkRequestRateLimiterHolderTest.java
  flint-core/src/test/scala/org/opensearch/flint/core/storage/BulkRequestRateLimiterTest.java
  flint-spark-integration/src/main/scala/org/apache/spark/sql/flint/config/FlintSparkConf.scala
  flint-spark-integration/src/test/scala/org/apache/spark/sql/flint/config/FlintSparkConfSuite.scala
Labels: 0.6, backport 0.5

#495 Abstract service for accessing Flint index metadata
  docs/index.md
  flint-commons/src/main/scala/org/opensearch/flint/common/FlintVersion.scala
  flint-commons/src/main/scala/org/opensearch/flint/common/metadata/FlintIndexMetadataService.java
  flint-commons/src/main/scala/org/opensearch/flint/common/metadata/FlintMetadata.scala
  flint-commons/src/main/scala/org/opensearch/flint/common/metadata/log/FlintMetadataLogEntry.scala
  flint-commons/src/test/scala/org/opensearch/flint/common/metadata/FlintMetadataSuite.scala
  flint-core/src/main/scala/org/opensearch/flint/core/FlintClient.java
  flint-core/src/main/scala/org/opensearch/flint/core/FlintOptions.java
  flint-core/src/main/scala/org/opensearch/flint/core/MetaData.scala
  flint-core/src/main/scala/org/opensearch/flint/core/metadata/FlintIndexMetadataServiceBuilder.java
  flint-core/src/main/scala/org/opensearch/flint/core/metadata/log/FlintMetadataLogServiceBuilder.java
  flint-core/src/main/scala/org/opensearch/flint/core/storage/FlintOpenSearchClient.java
  flint-core/src/main/scala/org/opensearch/flint/core/storage/FlintOpenSearchIndexMetadataService.scala
  flint-core/src/main/scala/org/opensearch/flint/core/storage/FlintOpenSearchMetadataLog.java
  flint-core/src/main/scala/org/opensearch/flint/core/storage/OpenSearchClientUtils.java
  flint-core/src/main/scala/org/opensearch/flint/core/table/OpenSearchCluster.java
  flint-core/src/main/scala/org/opensearch/flint/core/table/OpenSearchIndexTable.scala
  flint-core/src/test/scala/org/opensearch/flint/core/storage/FlintOpenSearchIndexMetadataServiceSuite.scala
  flint-core/src/test/scala/org/opensearch/flint/core/storage/OpenSearchClientUtilsSuite.scala
  flint-spark-integration/src/main/scala/org/apache/spark/sql/flint/FlintReadOnlyTable.scala
  flint-spark-integration/src/main/scala/org/apache/spark/sql/flint/config/FlintSparkConf.scala
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/FlintSpark.scala
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/FlintSparkIndex.scala
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/FlintSparkIndexFactory.scala
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/covering/FlintSparkCoveringIndex.scala
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/mv/FlintSparkMaterializedView.scala
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/skipping/FlintSparkSkippingIndex.scala
  flint-spark-integration/src/test/scala/org/opensearch/flint/spark/covering/ApplyFlintSparkCoveringIndexSuite.scala
  flint-spark-integration/src/test/scala/org/opensearch/flint/spark/skipping/FlintSparkSkippingIndexSuite.scala
  integ-test/src/integration/scala/org/opensearch/flint/core/FlintMetadataLogITSuite.scala
  integ-test/src/integration/scala/org/opensearch/flint/core/FlintOpenSearchClientSuite.scala
  integ-test/src/integration/scala/org/opensearch/flint/core/FlintOpenSearchIndexMetadataServiceITSuite.scala
  integ-test/src/integration/scala/org/opensearch/flint/spark/FlintSparkCoveringIndexITSuite.scala
  integ-test/src/integration/scala/org/opensearch/flint/spark/FlintSparkCoveringIndexSqlITSuite.scala
  integ-test/src/integration/scala/org/opensearch/flint/spark/FlintSparkIndexSqlITSuite.scala
  integ-test/src/integration/scala/org/opensearch/flint/spark/FlintSparkMaterializedViewITSuite.scala
  integ-test/src/integration/scala/org/opensearch/flint/spark/FlintSparkMaterializedViewSqlITSuite.scala
  integ-test/src/integration/scala/org/opensearch/flint/spark/FlintSparkSkippingIndexITSuite.scala
  integ-test/src/integration/scala/org/opensearch/flint/spark/FlintSparkSkippingIndexSqlITSuite.scala
  integ-test/src/integration/scala/org/opensearch/flint/spark/FlintSparkUpdateIndexITSuite.scala
  ppl-spark-integration/src/main/scala/org/opensearch/flint/spark/ppl/FlintSparkPPLParser.scala
Labels: maintenance, 0.6, backport 0.5, backport 0.5-nexus

#573 Update PPL describe command
  integ-test/src/integration/scala/org/opensearch/flint/spark/ppl/FlintSparkPPLBasicITSuite.scala
  ppl-spark-integration/README.md
  ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/CatalystQueryPlanVisitor.java
  ppl-spark-integration/src/test/scala/org/opensearch/flint/spark/ppl/PPLLogicalPlanBasicQueriesTranslatorTestSuite.scala
Labels: enhancement, 0.5, PPL, backport 0.5, backport 0.5-nexus

#549 Implement stddev_samp and stddev_pop ppl stats function
  integ-test/src/integration/scala/org/opensearch/flint/spark/ppl/FlintSparkPPLAggregationWithSpanITSuite.scala
  integ-test/src/integration/scala/org/opensearch/flint/spark/ppl/FlintSparkPPLAggregationsITSuite.scala
  ppl-spark-integration/README.md
  ppl-spark-integration/src/main/antlr4/OpenSearchPPLParser.g4
  ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/utils/AggregatorTranslator.java
  ppl-spark-integration/src/test/scala/org/opensearch/flint/spark/ppl/PPLLogicalPlanAggregationQueriesTranslatorTestSuite.scala
Labels: enhancement, 0.5, PPL, backport 0.5

#568 `Top` & `Rare` PPL commands support
  integ-test/src/integration/scala/org/opensearch/flint/spark/ppl/FlintSparkPPLTopAndRareITSuite.scala
  ppl-spark-integration/README.md
  ppl-spark-integration/src/main/antlr4/OpenSearchPPLParser.g4
  ppl-spark-integration/src/main/java/org/opensearch/sql/ast/tree/RareAggregation.java
  ppl-spark-integration/src/main/java/org/opensearch/sql/ast/tree/TopAggregation.java
  ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/CatalystQueryPlanVisitor.java
  ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/parser/AstBuilder.java
  ppl-spark-integration/src/test/scala/org/opensearch/flint/spark/ppl/PPLLogicalPlanTopAndRareQueriesTranslatorTestSuite.scala
Labels: enhancement, 0.5, PPL, backport 0.5, 0.5.1, backport 0.5-nexus

#564 Nested fields query fix
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/sql/FlintSparkSqlParser.scala
  integ-test/src/integration/scala/org/opensearch/flint/spark/FlintSparkSuite.scala
  integ-test/src/integration/scala/org/opensearch/flint/spark/ppl/FlintSparkPPLNestedFieldsITSuite.scala
  ppl-spark-integration/README.md
  ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/CatalystPlanContext.java
  ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/CatalystQueryPlanVisitor.java
  ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/utils/RelationUtils.java
  ppl-spark-integration/src/test/scala/org/opensearch/flint/spark/ppl/PPLLogicalPlanBasicQueriesTranslatorTestSuite.scala
  ppl-spark-integration/src/test/scala/org/opensearch/flint/spark/ppl/PPLLogicalPlanCorrelationQueriesTranslatorTestSuite.scala
  ppl-spark-integration/src/test/scala/org/opensearch/flint/spark/ppl/PPLLogicalPlanNestedQueriesTranslatorTestSuite.scala
Labels: PPL, backport 0.5, 0.5.1, backport 0.5-nexus

#547 Add percentile PPL function
  integ-test/src/integration/scala/org/opensearch/flint/spark/ppl/FlintSparkPPLAggregationWithSpanITSuite.scala
  integ-test/src/integration/scala/org/opensearch/flint/spark/ppl/FlintSparkPPLAggregationsITSuite.scala
  ppl-spark-integration/README.md
  ppl-spark-integration/src/main/antlr4/OpenSearchPPLLexer.g4
  ppl-spark-integration/src/main/antlr4/OpenSearchPPLParser.g4
  ppl-spark-integration/src/main/java/org/opensearch/sql/expression/function/BuiltinFunctionName.java
  ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/parser/AstExpressionBuilder.java
  ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/utils/AggregatorTranslator.java
  ppl-spark-integration/src/test/scala/org/opensearch/flint/spark/ppl/PPLLogicalPlanAggregationQueriesTranslatorTestSuite.scala
Labels: enhancement, 0.5, PPL, backport 0.5, backport 0.5-nexus

#577 Add conf for specifying flint checkpoint location
  docs/index.md
  flint-spark-integration/src/main/scala/org/apache/spark/sql/flint/config/FlintSparkConf.scala
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/FlintSparkIndexBuilder.scala
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/sql/covering/FlintSparkCoveringIndexAstBuilder.scala
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/sql/mv/FlintSparkMaterializedViewAstBuilder.scala
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/sql/skipping/FlintSparkSkippingIndexAstBuilder.scala
  flint-spark-integration/src/test/scala/org/opensearch/flint/spark/FlintSparkIndexBuilderSuite.scala
  integ-test/src/integration/scala/org/opensearch/flint/spark/FlintSparkCoveringIndexITSuite.scala
  integ-test/src/integration/scala/org/opensearch/flint/spark/FlintSparkIndexJobITSuite.scala
  integ-test/src/integration/scala/org/opensearch/flint/spark/FlintSparkIndexMonitorITSuite.scala
  integ-test/src/integration/scala/org/opensearch/flint/spark/FlintSparkIndexSqlITSuite.scala
  integ-test/src/integration/scala/org/opensearch/flint/spark/FlintSparkMaterializedViewITSuite.scala
  integ-test/src/integration/scala/org/opensearch/flint/spark/FlintSparkSkippingIndexITSuite.scala
  integ-test/src/integration/scala/org/opensearch/flint/spark/FlintSparkTransactionITSuite.scala
  integ-test/src/integration/scala/org/opensearch/flint/spark/FlintSparkUpdateIndexITSuite.scala
Labels: enhancement, 0.5, backport 0.5, backport 0.5-nexus

#548 Fix distinct_count ppl stats function
  integ-test/src/integration/scala/org/opensearch/flint/spark/ppl/FlintSparkPPLAggregationWithSpanITSuite.scala
  integ-test/src/integration/scala/org/opensearch/flint/spark/ppl/FlintSparkPPLAggregationsITSuite.scala
  ppl-spark-integration/README.md
  ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/utils/AggregatorTranslator.java
  ppl-spark-integration/src/test/scala/org/opensearch/flint/spark/ppl/PPLLogicalPlanAggregationQueriesTranslatorTestSuite.scala
Labels: enhancement, 0.5, PPL, backport 0.5, 0.5.1, backport 0.5-nexus

#595 PPL Parse command
  integ-test/src/integration/scala/org/opensearch/flint/spark/FlintSparkSuite.scala
  integ-test/src/integration/scala/org/opensearch/flint/spark/ppl/FlintSparkPPLParseITSuite.scala
  integ-test/src/integration/scala/org/opensearch/flint/spark/ppl/FlintSparkPPLTopAndRareITSuite.scala
  ppl-spark-integration/README.md
  ppl-spark-integration/src/main/antlr4/OpenSearchPPLParser.g4
  ppl-spark-integration/src/main/java/org/opensearch/sql/common/grok/Converter.java
  ppl-spark-integration/src/main/java/org/opensearch/sql/common/grok/Grok.java
  ppl-spark-integration/src/main/java/org/opensearch/sql/common/grok/GrokCompiler.java
  ppl-spark-integration/src/main/java/org/opensearch/sql/common/grok/GrokUtils.java
  ppl-spark-integration/src/main/java/org/opensearch/sql/common/grok/Match.java
  ppl-spark-integration/src/main/java/org/opensearch/sql/common/grok/exception/GrokException.java
  ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/CatalystPlanContext.java
  ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/CatalystQueryPlanVisitor.java
  ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/parser/AstBuilder.java
  ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/parser/AstExpressionBuilder.java
  ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/utils/ParseUtils.java
  ppl-spark-integration/src/test/scala/org/opensearch/flint/spark/ppl/PPLLogicalPlanParseTranslatorTestSuite.scala
  ppl-spark-integration/src/test/scala/org/opensearch/flint/spark/ppl/PPLLogicalPlanTopAndRareQueriesTranslatorTestSuite.scala
Labels: PPL, backport 0.5, 0.5.1

#381 [Refactor] Extend REPL to support external metadata storage and data storage
  flint-commons/src/main/scala/org/apache/spark/sql/QueryResultWriter.scala
  flint-commons/src/main/scala/org/apache/spark/sql/SessionManager.scala
  flint-commons/src/main/scala/org/apache/spark/sql/StatementExecutionManager.scala
  flint-commons/src/main/scala/org/opensearch/flint/common/model/FlintStatement.scala
  flint-commons/src/main/scala/org/opensearch/flint/common/model/InteractiveSession.scala
  flint-core/src/main/scala/org/opensearch/flint/core/storage/OpenSearchReader.java
  flint-spark-integration/src/main/scala/org/apache/spark/sql/flint/config/FlintSparkConf.scala
  integ-test/src/integration/scala/org/apache/spark/sql/FlintJobITSuite.scala
  integ-test/src/integration/scala/org/apache/spark/sql/FlintREPLITSuite.scala
  integ-test/src/integration/scala/org/opensearch/flint/OpenSearchSuite.scala
  spark-sql-application/src/main/scala/org/apache/spark/sql/CommandContext.scala
  spark-sql-application/src/main/scala/org/apache/spark/sql/CommandState.scala
  spark-sql-application/src/main/scala/org/apache/spark/sql/FlintJob.scala
  spark-sql-application/src/main/scala/org/apache/spark/sql/FlintJobExecutor.scala
  spark-sql-application/src/main/scala/org/apache/spark/sql/FlintREPL.scala
  spark-sql-application/src/main/scala/org/apache/spark/sql/JobOperator.scala
  spark-sql-application/src/main/scala/org/apache/spark/sql/QueryResultWriterImpl.scala
  spark-sql-application/src/main/scala/org/apache/spark/sql/SessionManagerImpl.scala
  spark-sql-application/src/main/scala/org/apache/spark/sql/StatementExecutionManagerImpl.scala
  spark-sql-application/src/test/scala/org/apache/spark/sql/FlintJobTest.scala
  spark-sql-application/src/test/scala/org/apache/spark/sql/FlintREPLTest.scala
Labels: enhancement, backport 0.5, 0.5.1, backport 0.5-nexus

#598 Add support of GroK command including default patterns
  integ-test/src/integration/scala/org/opensearch/flint/spark/ppl/FlintSparkPPLGrokITSuite.scala
  integ-test/src/integration/scala/org/opensearch/flint/spark/ppl/FlintSparkPPLParseITSuite.scala
  ppl-spark-integration/README.md
  ppl-spark-integration/src/main/java/org/opensearch/sql/common/grok/GrokUtils.java
  ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/CatalystPlanContext.java
  ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/CatalystQueryPlanVisitor.java
  ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/utils/ParseStrategy.java
  ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/utils/ParseUtils.java
  ppl-spark-integration/src/main/resources/patterns/firewalls
  ppl-spark-integration/src/main/resources/patterns/haproxy
  ppl-spark-integration/src/main/resources/patterns/java
  ppl-spark-integration/src/main/resources/patterns/linux-syslog
  ppl-spark-integration/src/main/resources/patterns/nagios
  ppl-spark-integration/src/main/resources/patterns/patterns
  ppl-spark-integration/src/main/resources/patterns/postfix
  ppl-spark-integration/src/main/resources/patterns/ruby
  ppl-spark-integration/src/test/scala/org/opensearch/flint/spark/ppl/PPLLogicalPlanGrokTranslatorTestSuite.scala
  ppl-spark-integration/src/test/scala/org/opensearch/flint/spark/ppl/PPLLogicalPlanParseTranslatorTestSuite.scala
Labels: 0.5, PPL, backport 0.5, 0.5.1, backport 0.5-nexus

#603 Add UT and IT for 2+ level aggregations PPL command
  integ-test/src/integration/scala/org/opensearch/flint/spark/ppl/FlintSparkPPLAggregationsITSuite.scala
  ppl-spark-integration/README.md
  ppl-spark-integration/src/test/scala/org/opensearch/flint/spark/ppl/PPLLogicalPlanAggregationQueriesTranslatorTestSuite.scala
Labels: PPL, backport 0.5, 0.5.1, backport 0.5-nexus

#543 Translate PPL `dedup` Command Part 2: allowedDuplication>1
  integ-test/src/integration/scala/org/opensearch/flint/spark/ppl/FlintSparkPPLDedupeITSuite.scala
  ppl-spark-integration/README.md
  ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/CatalystQueryPlanVisitor.java
  ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/utils/DedupeTransformer.java
  ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/utils/WindowSpecTransformer.java
  ppl-spark-integration/src/test/scala/org/opensearch/flint/spark/ppl/PPLLogicalPlanDedupeTranslatorTestSuite.scala
Labels: enhancement, PPL, backport 0.5, backport 0.5-nexus
