Repository opensearch-project/opensearch-spark, pull requests merged in 2024-04, with the labels that each got.

#285 Add AWS credentials provider for metadata access
  flint-core/src/main/scala/org/opensearch/flint/core/FlintClient.java
  flint-core/src/main/scala/org/opensearch/flint/core/FlintOptions.java
  flint-core/src/main/scala/org/opensearch/flint/core/auth/ResourceBasedAWSRequestSigningApacheInterceptor.java
  flint-core/src/main/scala/org/opensearch/flint/core/storage/FlintOpenSearchClient.java
  flint-core/src/test/scala/org/opensearch/flint/core/auth/ResourceBasedAWSRequestSigningApacheInterceptorTest.java
  flint-spark-integration/src/main/scala/org/apache/spark/sql/flint/config/FlintSparkConf.scala
  flint-spark-integration/src/test/scala/org/apache/spark/sql/flint/config/FlintSparkConfSuite.scala
Labels: feature, 0.3

#306 Unescape query from EMR spark submit parameter
  spark-sql-application/src/main/scala/org/apache/spark/sql/FlintJob.scala
  spark-sql-application/src/main/scala/org/apache/spark/sql/FlintJobExecutor.scala
  spark-sql-application/src/main/scala/org/apache/spark/sql/FlintREPL.scala
  spark-sql-application/src/test/scala/org/apache/spark/sql/FlintREPLTest.scala
Labels: bug, 0.3

#297 Improve pre-validation for Flint index refresh options
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/FlintSpark.scala
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/FlintSparkIndexBuilder.scala
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/FlintSparkValidationHelper.scala
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/refresh/AutoIndexRefresh.scala
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/refresh/FlintSparkIndexRefresh.scala
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/refresh/FullIndexRefresh.scala
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/refresh/IncrementalIndexRefresh.scala
  integ-test/src/test/scala/org/apache/spark/sql/SparkHiveSupportSuite.scala
  integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkCoveringIndexSqlITSuite.scala
  integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkIndexValidationITSuite.scala
  integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkMaterializedViewITSuite.scala
  integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkSkippingIndexITSuite.scala
  integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkSkippingIndexSqlITSuite.scala
  integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkUpdateIndexITSuite.scala
  project/Dependencies.scala
Labels: enhancement, 0.4

#308 Remove query log from job executor
  spark-sql-application/src/main/scala/org/apache/spark/sql/FlintJobExecutor.scala
Labels: backport 0.3

#301 Adding support to run integ tests on iceberg tables
  build.sbt
  integ-test/src/test/scala/org/apache/spark/sql/FlintJobITSuite.scala
  integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkCoveringIndexITSuite.scala
  integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkCoveringIndexSqlITSuite.scala
  integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkIndexJobITSuite.scala
  integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkIndexMonitorITSuite.scala
  integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkSkippingIndexITSuite.scala
  integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkSkippingIndexSqlITSuite.scala
  integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkSuite.scala
  integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkTransactionITSuite.scala
  integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkUpdateIndexITSuite.scala
  integ-test/src/test/scala/org/opensearch/flint/spark/iceberg/FlintSparkIcebergCoveringIndexITSuite.scala
  integ-test/src/test/scala/org/opensearch/flint/spark/iceberg/FlintSparkIcebergMaterializedViewITSuite.scala
  integ-test/src/test/scala/org/opensearch/flint/spark/iceberg/FlintSparkIcebergSkippingIndexITSuite.scala
  integ-test/src/test/scala/org/opensearch/flint/spark/iceberg/FlintSparkIcebergSuite.scala
  integ-test/src/test/scala/org/opensearch/flint/spark/ppl/FlintPPLSuite.scala
  integ-test/src/test/scala/org/opensearch/flint/spark/ppl/FlintSparkPPLAggregationWithSpanITSuite.scala
  integ-test/src/test/scala/org/opensearch/flint/spark/ppl/FlintSparkPPLAggregationsITSuite.scala
  integ-test/src/test/scala/org/opensearch/flint/spark/ppl/FlintSparkPPLBasicITSuite.scala
  integ-test/src/test/scala/org/opensearch/flint/spark/ppl/FlintSparkPPLCorrelationITSuite.scala
  integ-test/src/test/scala/org/opensearch/flint/spark/ppl/FlintSparkPPLFiltersITSuite.scala
  integ-test/src/test/scala/org/opensearch/flint/spark/ppl/FlintSparkPPLTimeWindowITSuite.scala
Labels: 0.4

#313 Allow non-existent checkpoint location path in index validation
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/FlintSparkValidationHelper.scala
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/refresh/AutoIndexRefresh.scala
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/refresh/IncrementalIndexRefresh.scala
  integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkIndexValidationITSuite.scala
Labels: bug, 0.4

#312 Clean shuffle data
  spark-sql-application/src/main/scala/org/apache/spark/sql/FlintJob.scala
  spark-sql-application/src/main/scala/org/apache/spark/sql/FlintJobExecutor.scala
  spark-sql-application/src/main/scala/org/apache/spark/sql/FlintREPL.scala
  spark-sql-application/src/main/scala/org/apache/spark/sql/JobOperator.scala
  spark-sql-application/src/main/scala/org/apache/spark/sql/util/ShuffleCleaner.scala
  spark-sql-application/src/test/scala/org/apache/spark/sql/FlintJobTest.scala
  spark-sql-application/src/test/scala/org/apache/spark/sql/util/CleanerFactoryTest.scala
Labels: 0.4

#303 Introduce aws sigv4a request signer
  build.sbt
  flint-core/src/main/scala/org/opensearch/flint/core/auth/AWSRequestSigV4ASigningApacheInterceptor.java
  flint-core/src/main/scala/org/opensearch/flint/core/auth/AWSRequestSigningApacheInterceptor.java
  flint-core/src/main/scala/org/opensearch/flint/core/auth/ResourceBasedAWSRequestSigningApacheInterceptor.java
  flint-core/src/main/scala/org/opensearch/flint/core/storage/FlintOpenSearchClient.java
  flint-core/src/test/scala/org/opensearch/flint/core/auth/AWSRequestSigV4ASigningApacheInterceptorTest.java
  flint-core/src/test/scala/org/opensearch/flint/core/auth/ResourceBasedAWSRequestSigningApacheInterceptorTest.java
  spark-sql-application/src/main/scala/org/apache/spark/sql/FlintREPL.scala
  spark-sql-application/src/test/scala/org/apache/spark/sql/FlintREPLTest.scala
Labels: backport 0.3

#318 Add covering index based query rewriter rule
  build.sbt
  docs/index.md
  flint-spark-integration/src/main/scala/org/apache/spark/sql/flint/config/FlintSparkConf.scala
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/FlintSparkOptimizer.scala
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/covering/ApplyFlintSparkCoveringIndex.scala
  flint-spark-integration/src/test/scala/org/opensearch/flint/spark/covering/ApplyFlintSparkCoveringIndexSuite.scala
  integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkCoveringIndexSqlITSuite.scala
  integ-test/src/test/scala/org/opensearch/flint/spark/iceberg/FlintSparkIcebergCoveringIndexITSuite.scala
Labels: feature, 0.4
