Repository opensearch-project/opensearch-spark, pull requests merged in 2024-05, with the labels that each got.

#326 Add maxExecutors configuration for streaming queries
  spark-sql-application/src/main/scala/org/apache/spark/sql/FlintJob.scala
  spark-sql-application/src/main/scala/org/apache/spark/sql/FlintJobExecutor.scala
  spark-sql-application/src/main/scala/org/apache/spark/sql/FlintREPL.scala
  spark-sql-application/src/test/scala/org/apache/spark/sql/FlintJobTest.scala
Labels: backport 0.3

#329 add batch_bytes configuration for Flint
  docs/index.md
  flint-core/src/main/scala/org/opensearch/flint/core/FlintOptions.java
  flint-core/src/main/scala/org/opensearch/flint/core/storage/FlintOpenSearchClient.java
  flint-core/src/main/scala/org/opensearch/flint/core/storage/FlintWriter.java
  flint-core/src/main/scala/org/opensearch/flint/core/storage/OpenSearchWriter.java
  flint-spark-integration/src/main/scala/org/apache/spark/sql/flint/FlintPartitionWriter.scala
  flint-spark-integration/src/main/scala/org/apache/spark/sql/flint/config/FlintSparkConf.scala
  flint-spark-integration/src/main/scala/org/apache/spark/sql/flint/json/FlintJacksonGenerator.scala
  flint-spark-integration/src/test/scala/org/apache/spark/sql/flint/config/FlintSparkConfSuite.scala
  integ-test/src/test/scala/org/apache/spark/FlintDataSourceV2ITSuite.scala
  spark-sql-application/src/main/scala/org/apache/spark/sql/FlintJobExecutor.scala
Labels: 0.4

#335 Improve flint error handling
  build.sbt
  flint-core/src/main/java/org/opensearch/flint/core/metrics/MetricConstants.java
  spark-sql-application/src/main/scala/org/apache/spark/sql/FlintJobExecutor.scala
  spark-sql-application/src/main/scala/org/apache/spark/sql/FlintREPL.scala
  spark-sql-application/src/main/scala/org/apache/spark/sql/JobOperator.scala
  spark-sql-application/src/test/scala/org/apache/spark/sql/FlintJobTest.scala
  spark-sql-application/src/test/scala/org/apache/spark/sql/FlintREPLTest.scala
Labels: enhancement, 0.3, backport 0.3

#338 [Manual Backport 0.3] Improve flint error handling (#335)
  build.sbt
  flint-core/src/main/java/org/opensearch/flint/core/metrics/MetricConstants.java
  spark-sql-application/src/main/scala/org/apache/spark/sql/FlintJobExecutor.scala
  spark-sql-application/src/main/scala/org/apache/spark/sql/FlintREPL.scala
  spark-sql-application/src/main/scala/org/apache/spark/sql/JobOperator.scala
  spark-sql-application/src/test/scala/org/apache/spark/sql/FlintJobTest.scala
  spark-sql-application/src/test/scala/org/apache/spark/sql/FlintREPLTest.scala
Labels: 0.3

#332 Fix incorrect result in show index statement
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/sql/FlintSparkSqlAstBuilder.scala
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/sql/covering/FlintSparkCoveringIndexAstBuilder.scala
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/sql/index/FlintSparkIndexAstBuilder.scala
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/sql/mv/FlintSparkMaterializedViewAstBuilder.scala
  integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkCoveringIndexSqlITSuite.scala
  integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkIndexSqlITSuite.scala
  integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkMaterializedViewSqlITSuite.scala
Labels: bug, 0.5

#343 Bump Flint version to 0.5.0
  README.md
  build.sbt
  docs/PPL-on-Spark.md
  docs/index.md
  flint-core/src/main/scala/org/opensearch/flint/core/FlintVersion.scala
Labels: 0.5

#346 Enhance index monitor to terminate streaming job on consecutive errors
  docs/index.md
  flint-spark-integration/src/main/scala/org/apache/spark/sql/flint/config/FlintSparkConf.scala
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/FlintSparkIndexMonitor.scala
  flint-spark-integration/src/test/scala/org/apache/spark/sql/flint/config/FlintSparkConfSuite.scala
  integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkIndexMonitorITSuite.scala
Labels: enhancement, 0.5, backport 0.4

#354 Bump Spark version to 3.5.1
  build.sbt
  flint-spark-integration/src/main/scala/org/apache/spark/sql/flint/FlintWrite.scala
  flint-spark-integration/src/main/scala/org/apache/spark/sql/flint/json/FlintJacksonParser.scala
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/skipping/FlintSparkSkippingFileIndex.scala
  flint-spark-integration/src/test/scala/org/opensearch/flint/spark/skipping/FlintSparkSkippingFileIndexSuite.scala
  integ-test/src/test/scala/org/apache/spark/FlintDataSourceV2ITSuite.scala
Labels: enhancement

#360 Bump Flint version to 0.4.1
  README.md
  build.sbt
  docs/PPL-on-Spark.md
  docs/index.md
  flint-core/src/main/scala/org/opensearch/flint/core/FlintVersion.scala
Labels: 0.4
