Repository opensearch-project/opensearch-spark, pull requests merged in 2024-12, with the labels that each got.

#947 Add support for serializing Spark's DecimalType
  docs/index.md
  flint-spark-integration/src/main/scala/org/apache/spark/sql/flint/datatype/FlintDataType.scala
  flint-spark-integration/src/test/scala/org/apache/spark/sql/flint/datatype/FlintDataTypeSuite.scala
  integ-test/src/integration/scala/org/opensearch/flint/spark/FlintSparkMaterializedViewSqlITSuite.scala
  integ-test/src/integration/scala/org/opensearch/flint/spark/FlintSparkSuite.scala
Labels: enhancement, backport 0.6, 0.7

#954 Add a script for importing GeoIP data
  docs/load_geoip_data.scala
  docs/opensearch-geoip.md
Labels: Lang:PPL, 0.7

#960 [BugFix] Fix ambiguous exception when type mismatch in fillnull command
  integ-test/src/integration/scala/org/opensearch/flint/spark/ppl/FlintSparkPPLFillnullITSuite.scala
  ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/CatalystQueryPlanVisitor.java
Labels: Lang:PPL, 0.7

#949 Wait after create index complete
  docs/index.md
  flint-core/src/main/scala/org/opensearch/flint/core/FlintOptions.java
  flint-core/src/main/scala/org/opensearch/flint/core/storage/FlintOpenSearchClient.java
  flint-spark-integration/src/main/scala/org/apache/spark/sql/flint/config/FlintSparkConf.scala
  flint-spark-integration/src/test/scala/org/apache/spark/sql/flint/config/FlintSparkConfSuite.scala
  integ-test/src/integration/scala/org/opensearch/flint/core/FlintOpenSearchClientSuite.scala
Labels: enhancement, backport 0.6, 0.7

#965 Add some instructions to use Spark EMR docker image
  docker/apache-spark-sample/.env
  docker/apache-spark-sample/docker-compose.yml
  docker/apache-spark-sample/spark-defaults.conf
  docker/spark-emr-sample/.env
  docker/spark-emr-sample/docker-compose.yml
  docker/spark-emr-sample/logging-conf/run-adot-collector.sh
  docker/spark-emr-sample/logging-conf/run-fluentd-spark.sh
  docker/spark-emr-sample/spark-conf/hive-site.xml
  docker/spark-emr-sample/spark-conf/log4j2.properties
  docker/spark-emr-sample/spark-conf/metrics.properties
  docker/spark-emr-sample/spark-conf/spark-defaults.conf
  docker/spark-emr-sample/spark-conf/spark-env.sh
  docker/spark-sample-app/build.sbt
  docker/spark-sample-app/src/main/scala/MyApp.scala
  docs/spark-docker.md
  docs/spark-emr-docker.md
Labels: documentation, Lang:PPL, 0.7

#976 Add setup-sbt in build workflow
  .github/workflows/test-and-build-workflow.yml
Labels: infrastructure

#951 Add retryable AOSS HTTP response
  flint-core/src/main/scala/org/opensearch/flint/core/http/FlintRetryOptions.java
  flint-core/src/main/scala/org/opensearch/flint/core/http/handler/HttpAOSSResultPredicate.java
  flint-core/src/test/scala/org/opensearch/flint/core/http/RetryableHttpAsyncClientSuite.scala
Labels: enhancement, backport 0.6, 0.7

#975 Refactor the `Alias` node to avoid ambiguity
  ppl-spark-integration/src/main/java/org/opensearch/sql/ast/expression/Alias.java
  ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/CatalystExpressionVisitor.java
  ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/parser/AstExpressionBuilder.java
Labels: maintenance, 0.7

#988 Add sourceQuery in metadata cache
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/metadatacache/FlintMetadataCache.scala
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/metadatacache/FlintOpenSearchMetadataCacheWriter.scala
  flint-spark-integration/src/test/scala/org/opensearch/flint/spark/metadatacache/FlintMetadataCacheSuite.scala
  integ-test/src/integration/scala/org/opensearch/flint/spark/metadatacache/FlintOpenSearchMetadataCacheWriterITSuite.scala
Labels: enhancement, 0.7

#971 PPL support json_delete, append functions
  docs/ppl-lang/functions/ppl-json.md
  integ-test/src/integration/scala/org/opensearch/flint/spark/ppl/FlintSparkPPLJsonFunctionITSuite.scala
  ppl-spark-integration/src/main/antlr4/OpenSearchPPLLexer.g4
  ppl-spark-integration/src/main/antlr4/OpenSearchPPLParser.g4
  ppl-spark-integration/src/main/java/org/opensearch/sql/expression/function/JsonUtils.java
  ppl-spark-integration/src/main/java/org/opensearch/sql/expression/function/SerializableUdf.java
  ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/CatalystExpressionVisitor.java
  ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/utils/BuiltinFunctionTransformer.java
  ppl-spark-integration/src/test/java/org/opensearch/sql/expression/function/SerializableIPUdfTest.java
  ppl-spark-integration/src/test/java/org/opensearch/sql/expression/function/SerializableJsonUdfTest.java
  ppl-spark-integration/src/test/scala/org/opensearch/flint/spark/ppl/PPLLogicalPlanJsonFunctionsTranslatorTestSuite.scala
  ppl-spark-integration/src/test/scala/org/opensearch/flint/spark/ppl/PPLLogicalPlanParseCidrmatchTestSuite.scala
Labels: Lang:PPL, 0.7

#871 PPL geoip function
  docs/ppl-lang/functions/ppl-ip.md
  docs/ppl-lang/planning/ppl-geoip-command.md
  integ-test/src/integration/scala/org/opensearch/flint/spark/FlintSparkSuite.scala
  integ-test/src/integration/scala/org/opensearch/flint/spark/ppl/FlintSparkPPLGeoipITSuite.scala
  ppl-spark-integration/src/main/antlr4/OpenSearchPPLLexer.g4
  ppl-spark-integration/src/main/antlr4/OpenSearchPPLParser.g4
  ppl-spark-integration/src/main/java/org/opensearch/sql/ast/AbstractNodeVisitor.java
  ppl-spark-integration/src/main/java/org/opensearch/sql/ast/tree/Eval.java
  ppl-spark-integration/src/main/java/org/opensearch/sql/ast/tree/GeoIp.java
  ppl-spark-integration/src/main/java/org/opensearch/sql/expression/function/SerializableUdf.java
  ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/CatalystQueryPlanVisitor.java
  ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/parser/AstBuilder.java
  ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/parser/AstExpressionBuilder.java
  ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/utils/GeoIpCatalystLogicalPlanTranslator.java
  ppl-spark-integration/src/test/scala/org/opensearch/flint/spark/ppl/PPLLogicalPlanGeoipFunctionTranslatorTestSuite.scala
Labels: Lang:PPL, 0.6
