Repository opensearch-project/opensearch-spark, pull requests merged in 2024-06, with the labels that each got.

#362 Transition Flint index state to Failed upon refresh job termination
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/FlintSpark.scala
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/FlintSparkIndexMonitor.scala
  integ-test/src/test/scala/org/apache/spark/sql/FlintJobITSuite.scala
  integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkIndexMonitorITSuite.scala
  spark-sql-application/src/main/scala/org/apache/spark/sql/JobOperator.scala
Labels: bug, 0.5, backport 0.4

#359 Pre-validate duplicate columns in materialized view query
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/mv/FlintSparkMaterializedView.scala
  integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkMaterializedViewSqlITSuite.scala
Labels: bug, 0.5

#370 Fix index state stuck in refreshing when streaming job exits early
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/FlintSparkIndexMonitor.scala
  integ-test/src/test/scala/org/apache/spark/sql/FlintJobITSuite.scala
  integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkIndexMonitorITSuite.scala
  spark-sql-application/src/main/scala/org/apache/spark/sql/JobOperator.scala
Labels: bug, 0.5, backport 0.4

#378 Read dataSourceName from `FlintOptions` and avoid passing as args
  flint-core/src/main/scala/org/opensearch/flint/core/FlintClient.java
  flint-core/src/main/scala/org/opensearch/flint/core/storage/FlintOpenSearchClient.java
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/FlintSpark.scala
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/FlintSparkIndexMonitor.scala
  integ-test/src/test/scala/org/opensearch/flint/core/FlintOpenSearchClientSuite.scala
  integ-test/src/test/scala/org/opensearch/flint/core/FlintTransactionITSuite.scala
Labels: maintenance, 0.5

#377 Refactor static method for OpenSearch client utils
  flint-core/src/main/scala/org/opensearch/flint/core/storage/FlintOpenSearchClient.java
  flint-core/src/main/scala/org/opensearch/flint/core/storage/FlintOpenSearchMetadataLog.java
  flint-core/src/main/scala/org/opensearch/flint/core/storage/OpenSearchClientUtils.java
Labels: maintenance, 0.5

#373 [Refactor] Introduce flint-commons for models and interfaces
  README.md
  build.sbt
  flint-commons/src/main/scala/org/opensearch/flint/data/ContextualDataStore.scala
  flint-commons/src/main/scala/org/opensearch/flint/data/FlintStatement.scala
  flint-commons/src/main/scala/org/opensearch/flint/data/InteractiveSession.scala
  flint-commons/src/test/scala/org/opensearch/flint/data/InteractiveSessionTest.scala
  flint-spark-integration/src/main/scala/org/opensearch/flint/app/FlintCommand.scala
  integ-test/src/test/scala/org/apache/spark/sql/FlintREPLITSuite.scala
  integ-test/src/test/scala/org/opensearch/flint/core/OpenSearchUpdaterSuite.scala
  spark-sql-application/src/main/scala/org/apache/spark/sql/FlintREPL.scala
  spark-sql-application/src/test/scala/org/apache/spark/sql/FlintREPLTest.scala
Labels: maintenance, 0.5

#379 Extract metadata log operations from FlintClient into FlintMetadataLogService
  flint-core/src/main/scala/org/opensearch/flint/core/FlintClient.java
  flint-core/src/main/scala/org/opensearch/flint/core/metadata/log/FlintMetadataLogService.java
  flint-core/src/main/scala/org/opensearch/flint/core/metadata/log/FlintMetadataLogServiceBuilder.java
  flint-core/src/main/scala/org/opensearch/flint/core/storage/FlintOpenSearchClient.java
  flint-core/src/main/scala/org/opensearch/flint/core/storage/FlintOpenSearchMetadataLog.java
  flint-core/src/main/scala/org/opensearch/flint/core/storage/FlintOpenSearchMetadataLogService.java
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/FlintSpark.scala
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/FlintSparkIndexMonitor.scala
  integ-test/src/test/scala/org/opensearch/flint/OpenSearchTransactionSuite.scala
  integ-test/src/test/scala/org/opensearch/flint/core/FlintMetadataLogITSuite.scala
  integ-test/src/test/scala/org/opensearch/flint/core/FlintOpenSearchClientSuite.scala
  integ-test/src/test/scala/org/opensearch/flint/core/FlintTransactionITSuite.scala
Labels: maintenance, 0.5

#366 Support nested indexed field in Flint skipping index SQL statement
  flint-spark-integration/src/main/antlr4/FlintSparkSqlExtensions.g4
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/sql/skipping/FlintSparkSkippingIndexAstBuilder.scala
  integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkSkippingIndexITSuite.scala
  integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkSkippingIndexSqlITSuite.scala
  integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkSuite.scala
Labels: bug, 0.5, backport 0.4

#389 Support custom metadata log service implementation
  build.sbt
  flint-commons/src/main/scala/org/opensearch/flint/common/metadata/log/FlintMetadataLog.java
  flint-commons/src/main/scala/org/opensearch/flint/common/metadata/log/FlintMetadataLogEntry.scala
  flint-commons/src/main/scala/org/opensearch/flint/common/metadata/log/FlintMetadataLogService.java
  flint-commons/src/main/scala/org/opensearch/flint/common/metadata/log/OptimisticTransaction.java
  flint-core/src/main/scala/org/opensearch/flint/core/FlintOptions.java
  flint-core/src/main/scala/org/opensearch/flint/core/metadata/FlintMetadata.scala
  flint-core/src/main/scala/org/opensearch/flint/core/metadata/log/DefaultOptimisticTransaction.java
  flint-core/src/main/scala/org/opensearch/flint/core/metadata/log/FlintMetadataLogServiceBuilder.java
  flint-core/src/main/scala/org/opensearch/flint/core/storage/FlintOpenSearchMetadataLog.java
  flint-core/src/main/scala/org/opensearch/flint/core/storage/FlintOpenSearchMetadataLogService.java
  flint-spark-integration/src/main/scala/org/apache/spark/sql/flint/config/FlintSparkConf.scala
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/FlintSpark.scala
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/FlintSparkIndex.scala
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/FlintSparkIndexMonitor.scala
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/covering/ApplyFlintSparkCoveringIndex.scala
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/covering/FlintSparkCoveringIndex.scala
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/mv/FlintSparkMaterializedView.scala
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/skipping/ApplyFlintSparkSkippingIndex.scala
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/skipping/FlintSparkSkippingIndex.scala
  flint-spark-integration/src/test/scala/org/opensearch/flint/spark/covering/ApplyFlintSparkCoveringIndexSuite.scala
  flint-spark-integration/src/test/scala/org/opensearch/flint/spark/skipping/ApplyFlintSparkSkippingIndexSuite.scala
  integ-test/src/test/scala/org/opensearch/flint/OpenSearchTransactionSuite.scala
  integ-test/src/test/scala/org/opensearch/flint/core/FlintMetadataLogITSuite.scala
  integ-test/src/test/scala/org/opensearch/flint/core/FlintTransactionITSuite.scala
  integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkIndexJobITSuite.scala
Labels: maintenance, 0.5

#391 Abstracting source relations for enhanced covering index rewriting
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/covering/ApplyFlintSparkCoveringIndex.scala
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/source/FlintSparkSourceRelation.scala
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/source/FlintSparkSourceRelationProvider.scala
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/source/file/FileSourceRelation.scala
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/source/file/FileSourceRelationProvider.scala
  flint-spark-integration/src/test/scala/org/opensearch/flint/spark/covering/ApplyFlintSparkCoveringIndexSuite.scala
Labels: maintenance, 0.5

#399 Add OpenSearchCatalog to enable direct access OpenSearch index in Spark SQL
  docs/opensearch-table.md
  flint-core/src/main/scala/org/opensearch/flint/core/FlintClient.java
  flint-core/src/main/scala/org/opensearch/flint/core/storage/FlintOpenSearchClient.java
  flint-spark-integration/src/main/scala/org/apache/spark/opensearch/catalog/OpenSearchCatalog.scala
  flint-spark-integration/src/main/scala/org/apache/spark/sql/flint/FlintReadOnlyTable.scala
  flint-spark-integration/src/main/scala/org/apache/spark/sql/flint/FlintTable.scala
  flint-spark-integration/src/test/scala/org/apache/spark/opensearch/catalog/OpenSearchCatalogTest.scala
  flint-spark-integration/src/test/scala/org/opensearch/flint/spark/covering/ApplyFlintSparkCoveringIndexSuite.scala
  integ-test/src/test/scala/org/apache/spark/opensearch/catalog/OpenSearchCatalogITSuite.scala
Labels: enhancement, backport 0.4

#348 Enhance Flint Spark API error reporting with centralized handler
  flint-core/src/main/scala/org/opensearch/flint/core/metadata/log/DefaultOptimisticTransaction.java
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/FlintSpark.scala
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/FlintSparkTransactionSupport.scala
  flint-spark-integration/src/test/scala/org/opensearch/flint/spark/FlintSparkTransactionSupportSuite.scala
  integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkTransactionITSuite.scala
Labels: enhancement, 0.5, backport 0.4

#393 Unquote text and identifiers in PPL parsing
  integ-test/src/test/scala/org/opensearch/flint/spark/ppl/FlintSparkPPLAggregationsITSuite.scala
  integ-test/src/test/scala/org/opensearch/flint/spark/ppl/FlintSparkPPLBasicITSuite.scala
  integ-test/src/test/scala/org/opensearch/flint/spark/ppl/FlintSparkPPLFiltersITSuite.scala
  integ-test/src/test/scala/org/opensearch/flint/spark/ppl/FlintSparkPPLTimeWindowITSuite.scala
  ppl-spark-integration/src/main/java/org/opensearch/sql/common/utils/StringUtils.java
  ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/parser/AstExpressionBuilder.java
  ppl-spark-integration/src/test/java/org/opensearch/sql/common/utils/StringUtilsTest.java
  ppl-spark-integration/src/test/scala/org/opensearch/flint/spark/ppl/PPLLogicalPlanAggregationQueriesTranslatorTestSuite.scala
  ppl-spark-integration/src/test/scala/org/opensearch/flint/spark/ppl/PPLLogicalPlanBasicQueriesTranslatorTestSuite.scala
  ppl-spark-integration/src/test/scala/org/opensearch/flint/spark/ppl/PPLLogicalPlanFiltersTranslatorTestSuite.scala
Labels: bug
