Repository opensearch-project/opensearch-spark, pull requests merged in 2024-07, with the labels that each got.

#410 handle MetaException with glue AccessDeniedException
  flint-core/src/main/java/org/opensearch/flint/core/logging/ExceptionMessages.scala
  spark-sql-application/src/main/scala/org/apache/spark/sql/FlintJobExecutor.scala
  spark-sql-application/src/test/scala/org/apache/spark/sql/FlintREPLTest.scala
Labels: backport 0.4

#402 support shard level split on read path
  docs/opensearch-table.md
  flint-core/src/main/scala/org/opensearch/flint/core/FlintClient.java
  flint-core/src/main/scala/org/opensearch/flint/core/storage/FlintOpenSearchClient.java
  flint-core/src/main/scala/org/opensearch/flint/core/storage/OpenSearchScrollReader.java
  flint-spark-integration/src/main/scala/org/apache/spark/opensearch/catalog/OpenSearchCatalog.scala
  flint-spark-integration/src/main/scala/org/apache/spark/opensearch/table/OpenSearchTable.scala
  flint-spark-integration/src/main/scala/org/apache/spark/opensearch/table/PartitionInfo.scala
  flint-spark-integration/src/main/scala/org/apache/spark/opensearch/table/ShardInfo.scala
  flint-spark-integration/src/main/scala/org/apache/spark/sql/flint/FlintPartitionReaderFactory.scala
  flint-spark-integration/src/main/scala/org/apache/spark/sql/flint/FlintReadOnlyTable.scala
  flint-spark-integration/src/main/scala/org/apache/spark/sql/flint/FlintScan.scala
  flint-spark-integration/src/main/scala/org/apache/spark/sql/flint/FlintScanBuilder.scala
  integ-test/src/test/scala/org/apache/spark/opensearch/catalog/OpenSearchCatalogITSuite.scala
  integ-test/src/test/scala/org/apache/spark/opensearch/table/OpenSearchCatalogSuite.scala
  integ-test/src/test/scala/org/apache/spark/opensearch/table/OpenSearchTableITSuite.scala
Labels: enhancement, 0.5

#414 Pre-validate checkpoint location write permission
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/FlintSparkValidationHelper.scala
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/refresh/AutoIndexRefresh.scala
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/refresh/IncrementalIndexRefresh.scala
  integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkIndexValidationITSuite.scala
Labels: enhancement, 0.5

#406 Separate metadata log entry data model and persistence
  build.sbt
  flint-commons/src/main/scala/org/opensearch/flint/common/metadata/log/FlintMetadataLog.java
  flint-commons/src/main/scala/org/opensearch/flint/common/metadata/log/FlintMetadataLogEntry.scala
  flint-core/src/main/scala/org/opensearch/flint/core/metadata/log/DefaultOptimisticTransaction.java
  flint-core/src/main/scala/org/opensearch/flint/core/storage/FlintMetadataLogEntryOpenSearchConverter.java
  flint-core/src/main/scala/org/opensearch/flint/core/storage/FlintOpenSearchMetadataLog.java
  flint-core/src/main/scala/org/opensearch/flint/core/storage/FlintOpenSearchMetadataLogService.java
  flint-core/src/test/scala/org/opensearch/flint/core/storage/FlintMetadataLogEntryOpenSearchConverterSuite.scala
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/FlintSpark.scala
  flint-spark-integration/src/test/scala/org/opensearch/flint/spark/covering/ApplyFlintSparkCoveringIndexSuite.scala
  integ-test/src/test/scala/org/opensearch/flint/OpenSearchTransactionSuite.scala
  integ-test/src/test/scala/org/opensearch/flint/core/FlintMetadataLogITSuite.scala
  integ-test/src/test/scala/org/opensearch/flint/core/FlintTransactionITSuite.scala
  integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkIndexJobITSuite.scala
Labels: maintenance, 0.5

#409 Enhance query rewriter rule to support partial covering index
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/FlintSparkQueryRewriteHelper.scala
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/covering/ApplyFlintSparkCoveringIndex.scala
  flint-spark-integration/src/test/scala/org/opensearch/flint/spark/covering/ApplyFlintSparkCoveringIndexSuite.scala
  integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkCoveringIndexSqlITSuite.scala
Labels: enhancement, 0.5

#433 Store error message for streaming job execution in Flint metadata log
  flint-core/src/main/java/org/opensearch/flint/core/logging/ExceptionMessages.java
  flint-core/src/main/java/org/opensearch/flint/core/logging/ExceptionMessages.scala
  flint-core/src/test/java/org/opensearch/flint/core/logging/ExceptionMessagesTest.java
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/FlintSparkIndexMonitor.scala
  integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkIndexMonitorITSuite.scala
Labels: enhancement, 0.5

#475 [Bugfix] Insights on query execution error
  integ-test/src/test/scala/org/apache/spark/sql/FlintREPLITSuite.scala
  spark-sql-application/src/main/scala/org/apache/spark/sql/FlintJobExecutor.scala
Labels: backport 0.4

#436 Add error output column to show Flint index statement
  docs/index.md
  flint-spark-integration/src/main/antlr4/FlintSparkSqlExtensions.g4
  flint-spark-integration/src/main/antlr4/SparkSqlBase.g4
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/sql/index/FlintSparkIndexAstBuilder.scala
  integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkIndexSqlITSuite.scala
Labels: enhancement, 0.5

#477 [Doc] Checklist to fix issue "could not find Docker environment" on macOS
  DEVELOPER_GUIDE.md
Labels: documentation
