Repository opensearch-project/opensearch-spark, pull requests merged in 2024-01, with the labels that each got.

#189 Add vacuum index API and SQL support
  docs/img/flint-core-index-state-transition.png
  docs/img/flint-spark-index-state-transition.png
  docs/index.md
  flint-core/src/main/scala/org/opensearch/flint/core/metadata/log/DefaultOptimisticTransaction.java
  flint-core/src/main/scala/org/opensearch/flint/core/metadata/log/FlintMetadataLog.java
  flint-core/src/main/scala/org/opensearch/flint/core/metadata/log/FlintMetadataLogEntry.scala
  flint-core/src/main/scala/org/opensearch/flint/core/metadata/log/OptimisticTransaction.java
  flint-core/src/main/scala/org/opensearch/flint/core/storage/FlintOpenSearchMetadataLog.java
  flint-spark-integration/src/main/antlr4/FlintSparkSqlExtensions.g4
  flint-spark-integration/src/main/antlr4/SparkSqlBase.g4
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/FlintSpark.scala
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/sql/covering/FlintSparkCoveringIndexAstBuilder.scala
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/sql/mv/FlintSparkMaterializedViewAstBuilder.scala
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/sql/skipping/FlintSparkSkippingIndexAstBuilder.scala
  integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkTransactionITSuite.scala
Labels: enhancement, 0.2

#208 Restrict the maximum size of value set by default limit
  docs/index.md
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/skipping/FlintSparkSkippingIndex.scala
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/skipping/FlintSparkSkippingStrategy.scala
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/skipping/minmax/MinMaxSkippingStrategy.scala
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/skipping/partition/PartitionSkippingStrategy.scala
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/skipping/valueset/ValueSetSkippingStrategy.scala
  flint-spark-integration/src/test/scala/org/opensearch/flint/spark/skipping/FlintSparkSkippingIndexSuite.scala
  flint-spark-integration/src/test/scala/org/opensearch/flint/spark/skipping/valueset/ValueSetSkippingStrategySuite.scala
  integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkSkippingIndexITSuite.scala
  integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkSuite.scala
Labels: bug, 0.2

#211 bug fix, support array datatype in MV
  flint-spark-integration/src/main/scala/org/apache/spark/sql/flint/datatype/FlintDataType.scala
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/mv/FlintSparkMaterializedView.scala
  flint-spark-integration/src/test/scala/org/apache/spark/sql/flint/datatype/FlintDataTypeSuite.scala
  integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkMaterializedViewITSuite.scala
  integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkMaterializedViewSqlITSuite.scala
  integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkSuite.scala
Labels: 0.2

#215 Percent-encode invalid flint index characters
  flint-core/src/main/scala/org/opensearch/flint/core/storage/FlintOpenSearchClient.java
  integ-test/src/test/scala/org/opensearch/flint/core/FlintOpenSearchClientSuite.scala
Labels: enhancement, 0.2, backport 0.1

#216 [Backport 0.1] Percent-encode invalid flint index characters (#215)
  flint-core/src/main/scala/org/opensearch/flint/core/storage/FlintOpenSearchClient.java
  integ-test/src/test/scala/org/opensearch/flint/core/FlintOpenSearchClientSuite.scala
Labels: enhancement

#222 GHA fix for backport and snapshot-publish
  .github/workflows/backport.yml
  .github/workflows/snapshot-publish.yml
Labels: infrastructure, backport 0.1

#224 Quote table name with backticks to escape special characters in spark.read.table()
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/FlintSpark.scala
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/FlintSparkIndex.scala
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/covering/FlintSparkCoveringIndex.scala
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/skipping/FlintSparkSkippingIndex.scala
  flint-spark-integration/src/test/scala/org/opensearch/flint/spark/covering/FlintSparkCoveringIndexSuite.scala
  flint-spark-integration/src/test/scala/org/opensearch/flint/spark/skipping/FlintSparkSkippingIndexSuite.scala
Labels: bug, backport 0.1

#210 Configure value set max size in SQL statement
  docs/index.md
  flint-spark-integration/src/main/antlr4/FlintSparkSqlExtensions.g4
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/FlintSparkIndexFactory.scala
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/skipping/FlintSparkSkippingIndex.scala
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/skipping/FlintSparkSkippingStrategy.scala
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/skipping/valueset/ValueSetSkippingStrategy.scala
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/sql/skipping/FlintSparkSkippingIndexAstBuilder.scala
  flint-spark-integration/src/test/scala/org/opensearch/flint/spark/skipping/FlintSparkSkippingIndexSuite.scala
  flint-spark-integration/src/test/scala/org/opensearch/flint/spark/skipping/valueset/ValueSetSkippingStrategySuite.scala
  integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkSkippingIndexITSuite.scala
  integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkSkippingIndexSqlITSuite.scala
Labels: enhancement, 0.2

#191 Change delete index API to logical delete
  docs/index.md
  flint-spark-integration/src/main/antlr4/FlintSparkSqlExtensions.g4
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/FlintSpark.scala
  integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkCoveringIndexITSuite.scala
  integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkCoveringIndexSqlITSuite.scala
  integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkIndexJobITSuite.scala
  integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkIndexJobSqlITSuite.scala
  integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkIndexMonitorITSuite.scala
  integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkIndexNameITSuite.scala
  integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkMaterializedViewITSuite.scala
  integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkMaterializedViewSqlITSuite.scala
  integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkSkippingIndexITSuite.scala
  integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkSkippingIndexSqlITSuite.scala
  integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkSuite.scala
  integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkTransactionITSuite.scala
Labels: maintenance, 0.2

#230 Trigger barkport workflow when a pull request merges
  .github/workflows/backport.yml
Labels: infrastructure

#209 Changes for adding default dimensions in CWSink.
  flint-core/src/main/java/org/opensearch/flint/core/metrics/reporter/DimensionedCloudWatchReporter.java
  flint-core/src/main/java/org/opensearch/flint/core/metrics/reporter/DimensionedName.java
  flint-core/src/test/java/opensearch/flint/core/metrics/reporter/DimensionedCloudWatchReporterTest.java
  flint-core/src/test/java/opensearch/flint/core/metrics/reporter/DimensionedNameTest.java
Labels: 0.2

#228 Refactor Flint index refresh mode
  docs/index.md
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/FlintSpark.scala
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/sql/covering/FlintSparkCoveringIndexAstBuilder.scala
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/sql/mv/FlintSparkMaterializedViewAstBuilder.scala
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/sql/skipping/FlintSparkSkippingIndexAstBuilder.scala
  integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkCoveringIndexITSuite.scala
  integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkIndexMonitorITSuite.scala
  integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkMaterializedViewITSuite.scala
  integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkSkippingIndexITSuite.scala
  integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkSkippingIndexSqlITSuite.scala
  integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkTransactionITSuite.scala
Labels: maintenance, 0.2

#236 Fix Lychee Link Checker Error
  .github/workflows/link-checker.yml
  .lychee.excludes
Labels: infrastructure, backport 0.1
