Repository opensearch-project/opensearch-spark, pull requests merged in 2024-02, with the labels that each got.

#229 Add OpenSearch metrics
  build.sbt
  flint-core/src/main/java/org/opensearch/flint/core/IRestHighLevelClient.java
  flint-core/src/main/java/org/opensearch/flint/core/RestHighLevelClientWrapper.java
  flint-core/src/main/java/org/opensearch/flint/core/metrics/MetricConstants.java
  flint-core/src/main/java/org/opensearch/flint/core/metrics/MetricsUtil.java
  flint-core/src/main/java/org/opensearch/flint/core/metrics/reporter/DimensionedCloudWatchReporter.java
  flint-core/src/main/scala/apache/spark/metrics/source/FlintMetricSource.scala
  flint-core/src/main/scala/org/opensearch/flint/core/FlintClient.java
  flint-core/src/main/scala/org/opensearch/flint/core/storage/FlintOpenSearchClient.java
  flint-core/src/main/scala/org/opensearch/flint/core/storage/FlintOpenSearchMetadataLog.java
  flint-core/src/main/scala/org/opensearch/flint/core/storage/OpenSearchReader.java
  flint-core/src/main/scala/org/opensearch/flint/core/storage/OpenSearchScrollReader.java
  flint-core/src/main/scala/org/opensearch/flint/core/storage/OpenSearchUpdater.java
  flint-core/src/main/scala/org/opensearch/flint/core/storage/OpenSearchWriter.java
  flint-core/src/test/java/opensearch/flint/core/metrics/reporter/DimensionedCloudWatchReporterTest.java
  flint-core/src/test/java/org/opensearch/flint/core/metrics/MetricsUtilTest.java
  spark-sql-application/src/main/scala/org/apache/spark/sql/FlintREPL.scala
  spark-sql-application/src/main/scala/org/apache/spark/sql/OSClient.scala
Labels: 0.2

#241 Fix recover index bug when Flint data index is deleted accidentally
  docs/index.md
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/FlintSpark.scala
  integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkTransactionITSuite.scala
  spark-sql-application/src/main/scala/org/apache/spark/sql/JobOperator.scala
Labels: bug, 0.2, backport 0.1

#213 Support struct field as indexed column
  flint-spark-integration/src/main/scala/org/apache/spark/sql/flint/package.scala
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/FlintSparkIndexBuilder.scala
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/skipping/FlintSparkSkippingStrategy.scala
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/skipping/minmax/MinMaxSkippingStrategy.scala
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/skipping/partition/PartitionSkippingStrategy.scala
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/skipping/valueset/ValueSetSkippingStrategy.scala
  flint-spark-integration/src/test/scala/org/opensearch/flint/spark/FlintSparkIndexBuilderSuite.scala
  integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkSkippingIndexITSuite.scala
Labels: bug, 0.2

#242 Implement BloomFilter skipping index building logic
  docs/index.md
  flint-core/src/main/java/org/opensearch/flint/core/field/bloomfilter/BloomFilter.java
  flint-core/src/main/java/org/opensearch/flint/core/field/bloomfilter/classic/BitArray.java
  flint-core/src/main/java/org/opensearch/flint/core/field/bloomfilter/classic/ClassicBloomFilter.java
  flint-core/src/main/java/org/opensearch/flint/core/field/bloomfilter/classic/Murmur3_x86_32.java
  flint-core/src/test/java/org/opensearch/flint/core/field/bloomfilter/classic/ClassicBloomFilterTest.java
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/FlintSparkIndexFactory.scala
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/skipping/FlintSparkSkippingIndex.scala
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/skipping/FlintSparkSkippingStrategy.scala
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/skipping/bloomfilter/BloomFilterAgg.scala
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/skipping/bloomfilter/BloomFilterSkippingStrategy.scala
  flint-spark-integration/src/test/scala/org/opensearch/flint/spark/skipping/bloomfilter/BloomFilterSkippingStrategySuite.scala
  integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkSkippingIndexITSuite.scala
Labels: enhancement, 0.2

#234 Support on-demand incremental refresh
  docs/index.md
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/FlintSpark.scala
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/FlintSparkIndexOptions.scala
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/refresh/AutoIndexRefresh.scala
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/refresh/FlintSparkIndexRefresh.scala
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/refresh/FullIndexRefresh.scala
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/refresh/IncrementalIndexRefresh.scala
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/sql/covering/FlintSparkCoveringIndexAstBuilder.scala
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/sql/mv/FlintSparkMaterializedViewAstBuilder.scala
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/sql/skipping/FlintSparkSkippingIndexAstBuilder.scala
  flint-spark-integration/src/test/scala/org/opensearch/flint/spark/FlintSparkIndexOptionsSuite.scala
  flint-spark-integration/src/test/scala/org/opensearch/flint/spark/FlintSparkIndexRefreshSuite.scala
  flint-spark-integration/src/test/scala/org/opensearch/flint/spark/mv/FlintSparkMaterializedViewSuite.scala
  integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkCoveringIndexITSuite.scala
  integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkCoveringIndexSqlITSuite.scala
  integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkMaterializedViewITSuite.scala
  integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkMaterializedViewSqlITSuite.scala
  integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkSkippingIndexITSuite.scala
  integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkSkippingIndexSqlITSuite.scala
  integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkTransactionITSuite.scala
Labels: enhancement, 0.2

#245 Fix Session state bug and improve Query Efficiency in REPL
  build.sbt
  flint-core/src/main/scala/org/opensearch/flint/core/FlintOptions.java
  flint-core/src/main/scala/org/opensearch/flint/core/storage/OpenSearchQueryReader.java
  flint-core/src/main/scala/org/opensearch/flint/core/storage/OpenSearchReader.java
  flint-core/src/test/java/org/opensearch/flint/core/metrics/reporter/DimensionUtilsTest.java
  flint-spark-integration/src/main/scala/org/apache/spark/sql/flint/config/FlintSparkConf.scala
  flint-spark-integration/src/main/scala/org/opensearch/flint/app/FlintInstance.scala
  integ-test/src/test/scala/org/apache/spark/sql/FlintJobITSuite.scala
  integ-test/src/test/scala/org/apache/spark/sql/FlintREPLITSuite.scala
  integ-test/src/test/scala/org/apache/spark/sql/JobTest.scala
  integ-test/src/test/scala/org/apache/spark/sql/REPLResult.scala
  integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkSuite.scala
  integ-test/src/test/scala/org/opensearch/flint/spark/ppl/FlintSparkPPLCorrelationITSuite.scala
  integ-test/src/test/scala/org/opensearch/flint/spark/ppl/FlintSparkPPLFiltersITSuite.scala
  spark-sql-application/src/main/scala/org/apache/spark/sql/FlintJob.scala
  spark-sql-application/src/main/scala/org/apache/spark/sql/FlintJobExecutor.scala
  spark-sql-application/src/main/scala/org/apache/spark/sql/FlintREPL.scala
  spark-sql-application/src/main/scala/org/apache/spark/sql/JobOperator.scala
  spark-sql-application/src/main/scala/org/apache/spark/sql/OSClient.scala
  spark-sql-application/src/main/scala/org/apache/spark/sql/util/EnvironmentProvider.scala
  spark-sql-application/src/main/scala/org/apache/spark/sql/util/RealEnvironment.scala
  spark-sql-application/src/test/scala/org/apache/spark/sql/FlintREPLTest.scala
  spark-sql-application/src/test/scala/org/apache/spark/sql/util/MockEnvironment.scala
Labels: backport 0.1

#247 [Backport 0.1] Fix recover index bug when Flint data index is deleted accidentally
  docs/index.md
  flint-core/src/main/scala/org/opensearch/flint/core/metadata/log/DefaultOptimisticTransaction.java
  flint-core/src/main/scala/org/opensearch/flint/core/metadata/log/FlintMetadataLog.java
  flint-core/src/main/scala/org/opensearch/flint/core/metadata/log/OptimisticTransaction.java
  flint-core/src/main/scala/org/opensearch/flint/core/storage/FlintOpenSearchMetadataLog.java
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/FlintSpark.scala
  integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkTransactionITSuite.scala
  spark-sql-application/src/main/scala/org/apache/spark/sql/JobOperator.scala
Labels: 0.1.1

#240 Add interactive job metrics
  flint-core/src/main/java/org/opensearch/flint/core/metrics/MetricConstants.java
  flint-core/src/main/java/org/opensearch/flint/core/metrics/MetricsUtil.java
  flint-core/src/test/java/org/opensearch/flint/core/metrics/MetricsUtilTest.java
  spark-sql-application/src/main/scala/org/apache/spark/sql/FlintJobExecutor.scala
  spark-sql-application/src/main/scala/org/apache/spark/sql/FlintREPL.scala
  spark-sql-application/src/test/scala/org/apache/spark/sql/FlintREPLTest.scala
Labels: 0.1.1
