Repository opensearch-project/opensearch-spark, pull requests merged in 2025-05, with the labels that each got.

#1101 Adding _source and schema merging to index_mappings
  docs/index.md
  flint-core/src/main/scala/org/opensearch/flint/core/storage/FlintOpenSearchIndexMetadataService.scala
  flint-core/src/test/scala/org/opensearch/flint/core/storage/FlintOpenSearchIndexMetadataServiceSuite.scala
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/FlintSparkIndexOptions.scala
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/covering/FlintSparkCoveringIndex.scala
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/mv/FlintSparkMaterializedView.scala
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/skipping/FlintSparkSkippingIndex.scala
  integ-test/src/integration/scala/org/opensearch/flint/spark/FlintSparkCoveringIndexSqlITSuite.scala
  integ-test/src/integration/scala/org/opensearch/flint/spark/FlintSparkMaterializedViewSqlITSuite.scala
  integ-test/src/integration/scala/org/opensearch/flint/spark/FlintSparkSkippingIndexITSuite.scala
  integ-test/src/integration/scala/org/opensearch/flint/spark/FlintSparkSkippingIndexSqlITSuite.scala
Labels: enhancement, backport 0.x, backport 0.7

#1152 modified workflow and add last commit id to the metadata file
  .github/workflows/snapshot-publish.yml
  flint-commons/src/main/scala/org/opensearch/flint/common/FlintVersion.scala
Labels: infrastructure, backport 0.x, backport 0.7

#1135 Adaptive rate control enhancement
  .github/workflows/test-and-build-workflow.yml
  docs/index.md
  flint-core/src/main/java/org/opensearch/flint/core/metrics/MetricConstants.java
  flint-core/src/main/scala/org/opensearch/flint/core/FlintOptions.java
  flint-core/src/main/scala/org/opensearch/flint/core/storage/BulkRequestRateLimiter.java
  flint-core/src/main/scala/org/opensearch/flint/core/storage/BulkRequestRateLimiterImpl.java
  flint-core/src/main/scala/org/opensearch/flint/core/storage/OpenSearchBulkWrapper.java
  flint-core/src/main/scala/org/opensearch/flint/core/storage/OpenSearchClientUtils.java
  flint-core/src/main/scala/org/opensearch/flint/core/storage/RequestRateMeter.java
  flint-core/src/main/scala/org/opensearch/flint/core/storage/ratelimit/BulkRequestRateLimiter.java
  flint-core/src/main/scala/org/opensearch/flint/core/storage/ratelimit/BulkRequestRateLimiterHolder.java
  flint-core/src/main/scala/org/opensearch/flint/core/storage/ratelimit/BulkRequestRateLimiterImpl.java
  flint-core/src/main/scala/org/opensearch/flint/core/storage/ratelimit/BulkRequestRateLimiterNoop.java
  flint-core/src/main/scala/org/opensearch/flint/core/storage/ratelimit/FeedbackHandler.java
  flint-core/src/main/scala/org/opensearch/flint/core/storage/ratelimit/RequestFeedback.java
  flint-core/src/main/scala/org/opensearch/flint/core/storage/ratelimit/RetryableFailureRequestFeedback.java
  flint-core/src/main/scala/org/opensearch/flint/core/storage/ratelimit/SuccessRequestFeedback.java
  flint-core/src/main/scala/org/opensearch/flint/core/storage/ratelimit/TimeoutRequestFeedback.java
  flint-core/src/test/java/org/opensearch/flint/core/storage/RequestRateMeterTest.java
  flint-core/src/test/scala/org/opensearch/flint/core/http/RetryableHttpAsyncClientSuite.scala
  flint-core/src/test/scala/org/opensearch/flint/core/storage/BulkRequestRateLimiterHolderTest.java
  flint-core/src/test/scala/org/opensearch/flint/core/storage/BulkRequestRateLimiterTest.java
  flint-core/src/test/scala/org/opensearch/flint/core/storage/OpenSearchBulkWrapperTest.java
  flint-core/src/test/scala/org/opensearch/flint/core/storage/OpenSearchClientUtilsSuite.scala
  flint-core/src/test/scala/org/opensearch/flint/core/storage/ratelimit/BulkRequestRateLimiterHolderTest.java
  flint-core/src/test/scala/org/opensearch/flint/core/storage/ratelimit/BulkRequestRateLimiterTest.java
  flint-spark-integration/src/test/scala/org/apache/spark/sql/flint/config/FlintSparkConfSuite.scala
Labels: backport 0.x, backport 0.7

#1170 Correct the behaviors of function `isempty` and `isblank`
  docs/ppl-lang/functions/ppl-condition.md
  integ-test/src/integration/scala/org/opensearch/flint/spark/ppl/FlintSparkPPLBuiltinFunctionITSuite.scala
  ppl-spark-integration/src/main/antlr4/OpenSearchPPLLexer.g4
  ppl-spark-integration/src/main/antlr4/OpenSearchPPLParser.g4
  ppl-spark-integration/src/main/java/org/opensearch/sql/ast/AbstractNodeVisitor.java
  ppl-spark-integration/src/main/java/org/opensearch/sql/ast/expression/IsEmpty.java
  ppl-spark-integration/src/main/java/org/opensearch/sql/expression/function/BuiltinFunctionName.java
  ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/CatalystExpressionVisitor.java
  ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/parser/AstExpressionBuilder.java
  ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/utils/BuiltinFunctionTransformer.java
Labels: backport 0.x

#1148 Fields identifier in PPL should be case sensitive
  docker/integ-test/queries.scala
  e2e-test/src/test/resources/opensearch/queries/ppl/query_123.ppl
  e2e-test/src/test/resources/opensearch/queries/ppl/query_124.ppl
  e2e-test/src/test/resources/spark/queries/ppl/query_123.ppl
  e2e-test/src/test/resources/spark/queries/ppl/query_124.ppl
  integ-test/script/test_cases.csv
  integ-test/src/integration/resources/opensearch/dashboards_sample_data_flights_tests.json
  integ-test/src/integration/scala/org/apache/spark/opensearch/table/OpenSearchDashboardITSuite.scala
  integ-test/src/integration/scala/org/opensearch/flint/spark/ppl/FlintSparkPPLLookupITSuite.scala
  ppl-spark-integration/src/main/scala/org/opensearch/flint/spark/ppl/FlintSparkPPLParser.scala
Labels: backport 0.x, backport 0.7

#1177 Download and add the last commit_id to maven-metadata.xml
  .github/workflows/snapshot-publish.yml
Labels: backport 0.x, backport 0.7
