Repository opensearch-project/opensearch-spark, pull requests merged in 2025-04, with the labels that each got.

#1094 Fix antlr4 parser issues
  ppl-spark-integration/src/main/antlr4/OpenSearchPPLLexer.g4
  ppl-spark-integration/src/main/antlr4/OpenSearchPPLParser.g4
Labels: bug, backport 0.x

#1103 Support QUARTER interval in date_add/date_sub
  integ-test/src/integration/scala/org/opensearch/flint/spark/ppl/FlintSparkPPLBuiltInDateTimeFunctionITSuite.scala
  ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/utils/BuiltinFunctionTransformer.java
Labels: backport 0.x

#1106 Call processDataframe before writeDataFrame for non Streaming Or Batch queries
  spark-sql-application/src/main/scala/org/apache/spark/sql/JobOperator.scala
Labels: backport 0.x, backport 0.7

#1100 Support OpenSearch ip field type (UDT)
  build.sbt
  docs/opensearch-table.md
  flint-spark-integration/src/main/scala/org/apache/spark/sql/flint/datatype/FlintDataType.scala
  flint-spark-integration/src/main/scala/org/apache/spark/sql/flint/json/FlintJacksonParser.scala
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/FlintSparkExtensions.scala
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/udt/IPAddress.scala
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/udt/IPAddressUDT.scala
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/udt/IPFunctions.scala
  flint-spark-integration/src/test/scala/org/opensearch/flint/spark/udt/IPAddressTest.scala
  integ-test/src/integration/scala/org/apache/spark/opensearch/table/OpenSearchTableQueryITSuite.scala
  integ-test/src/integration/scala/org/opensearch/flint/OpenSearchSuite.scala
Labels: DataSource:OpenSearch, backport 0.x

#1115 Add geo_point OpenSearch type support
  build.sbt
  docs/opensearch-table.md
  flint-spark-integration/src/main/scala/org/apache/spark/sql/flint/datatype/FlintDataType.scala
  flint-spark-integration/src/main/scala/org/apache/spark/sql/flint/json/FlintJacksonParser.scala
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/FlintSparkExtensions.scala
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/udt/GeoPoint.scala
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/udt/GeoPointConverter.scala
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/udt/GeoPointUDT.scala
  flint-spark-integration/src/test/scala/org/apache/spark/sql/flint/datatype/FlintDataTypeSuite.scala
  flint-spark-integration/src/test/scala/org/opensearch/flint/spark/udt/GeoPointConverterSuite.scala
  integ-test/src/integration/scala/org/apache/spark/opensearch/table/OpenSearchTableQueryITSuite.scala
  integ-test/src/integration/scala/org/opensearch/flint/OpenSearchSuite.scala
Labels: DataSource:OpenSearch, backport 0.x

#1105 Pass execptionType in error message
  integ-test/src/integration/scala/org/apache/spark/sql/FlintREPLITSuite.scala
  spark-sql-application/src/main/scala/org/apache/spark/sql/FlintJobExecutor.scala
  spark-sql-application/src/main/scala/org/apache/spark/sql/JobOperator.scala
  spark-sql-application/src/test/scala/org/apache/spark/sql/FlintREPLTest.scala
Labels: backport 0.x, backport 0.7

#1125 Fix AWS EMR-S integration test
  DEVELOPER_GUIDE.md
  integ-test/src/aws-integration/scala/org/opensearch/flint/spark/aws/AWSEmrServerlessAccessTestSuite.scala
Labels: testing, backport 0.x

#1124 Add account dimension to bytesRead metrics
  flint-core/src/main/scala/org/opensearch/flint/core/FlintOptions.java
  flint-core/src/main/scala/org/opensearch/flint/core/metrics/MetricsSparkListener.scala
  flint-core/src/test/scala/org/opensearch/flint/core/metrics/MetricsSparkListenerTest.scala
Labels: backport 0.x, backport 0.7

#1074 Adding fast refresh setting during index creation
  integ-test/src/integration/scala/org/apache/spark/opensearch/index/OpenSearchIndexITSuite.scala
  integ-test/src/integration/scala/org/apache/spark/sql/JobTest.scala
  integ-test/src/integration/scala/org/opensearch/flint/OpenSearchSuite.scala
  spark-sql-application/src/main/scala/org/apache/spark/sql/FlintJobExecutor.scala
  spark-sql-application/src/main/scala/org/apache/spark/sql/OSClient.scala
Labels: backport 0.x, backport 0.7
