Repository opensearch-project/opensearch-spark, pull requests merged in 2025-01, with the labels that each got.

#990 PPL command implementation for `appendCol`
  docs/ppl-lang/PPL-Example-Commands.md
  docs/ppl-lang/README.md
  docs/ppl-lang/ppl-appendcol-command.md
  integ-test/src/integration/scala/org/opensearch/flint/spark/ppl/FlintSparkPPLAppendColITSuite.scala
  ppl-spark-integration/src/main/antlr4/OpenSearchPPLLexer.g4
  ppl-spark-integration/src/main/antlr4/OpenSearchPPLParser.g4
  ppl-spark-integration/src/main/java/org/opensearch/sql/ast/AbstractNodeVisitor.java
  ppl-spark-integration/src/main/java/org/opensearch/sql/ast/tree/AppendCol.java
  ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/CatalystQueryPlanVisitor.java
  ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/parser/AstBuilder.java
  ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/utils/AppendColCatalystUtils.java
  ppl-spark-integration/src/test/scala/org/opensearch/flint/spark/ppl/PPLLogicalPlanAppendColCommandTranslatorTestSuite.scala
Labels: Lang:PPL, 0.7

#946 Enhance CV and MV idempotency via deterministic ID generation
  docs/index.md
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/FlintSparkIndex.scala
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/FlintSparkIndexOptions.scala
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/covering/FlintSparkCoveringIndex.scala
  flint-spark-integration/src/main/scala/org/opensearch/flint/spark/mv/FlintSparkMaterializedView.scala
  flint-spark-integration/src/test/scala/org/apache/spark/FlintSuite.scala
  flint-spark-integration/src/test/scala/org/opensearch/flint/spark/FlintSparkIndexOptionsSuite.scala
  flint-spark-integration/src/test/scala/org/opensearch/flint/spark/FlintSparkIndexSuite.scala
  flint-spark-integration/src/test/scala/org/opensearch/flint/spark/covering/FlintSparkCoveringIndexSuite.scala
  flint-spark-integration/src/test/scala/org/opensearch/flint/spark/mv/FlintSparkMaterializedViewSuite.scala
  integ-test/src/integration/scala/org/opensearch/flint/spark/FlintSparkCoveringIndexSqlITSuite.scala
  integ-test/src/integration/scala/org/opensearch/flint/spark/FlintSparkMaterializedViewSqlITSuite.scala
Labels: enhancement, 0.7

#1013 Update to upload-artifact@v4
  .github/workflows/test-and-build-workflow.yml
Labels: infrastructure

#994 #963 Unimplemented PPL Sort Syntax
  docs/ppl-lang/PPL-Example-Commands.md
  docs/ppl-lang/ppl-parse-command.md
  integ-test/src/integration/scala/org/opensearch/flint/spark/ppl/FlintSparkPPLParseITSuite.scala
  ppl-spark-integration/src/main/antlr4/OpenSearchPPLLexer.g4
  ppl-spark-integration/src/main/antlr4/OpenSearchPPLParser.g4
  ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/parser/AstExpressionBuilder.java
  ppl-spark-integration/src/test/scala/org/opensearch/flint/spark/ppl/PPLLogicalPlanParseTranslatorTestSuite.scala
Labels: Lang:PPL, 0.7

#1015 Unshade auth-crt due to known issue
  build.sbt
Labels: backport 0.6, 0.6.1

#1002 Add stalled PRs workflow
  .github/workflows/stalled.yml
Labels: infrastructure

#995 Introduce basic sanity test for MV used by Observability Integrations
  integ-test/src/integration/resources/aws-logs/cloud_trail.sql
  integ-test/src/integration/resources/aws-logs/vpc_flow.sql
  integ-test/src/integration/resources/aws-logs/waf.sql
  integ-test/src/integration/scala/org/opensearch/flint/spark/FlintSparkMaterializedViewIntegrationsITSuite.scala
  integ-test/src/integration/scala/org/opensearch/flint/spark/FlintSparkMaterializedViewSqlITSuite.scala
Labels: testing, 0.7

#1003 Docker integ test with async API
  docker/integ-test/.env
  docker/integ-test/configuration-updater/apply-configuration.sh
  docker/integ-test/docker-compose.yml
  docker/integ-test/metastore/Dockerfile
  docker/integ-test/metastore/hive-log4j2.properties
  docker/integ-test/metastore/hive-site.xml
  docker/integ-test/opensearch/Dockerfile
  docker/integ-test/opensearch/docker-command-runner.sh
  docker/integ-test/opensearch/emr-src/com/amazonaws/services/emrserverless/AWSEMRServerlessClientBuilder.java
  docker/integ-test/opensearch/emr-src/org/opensearch/spark/emrserverless/DockerEMRServerlessClient.java
  docker/integ-test/opensearch/log4j2.properties
  docker/integ-test/opensearch/opensearch-docker-it-entrypoint.sh
  docker/integ-test/opensearch/opensearch_security.policy
  docker/integ-test/spark-submit/Dockerfile
  docker/integ-test/spark-submit/spark-defaults.conf
  docker/integ-test/spark/Dockerfile
  docker/integ-test/spark/log4j2.properties
  docker/integ-test/spark/spark-defaults.conf
  docker/integ-test/spark/spark-master-entrypoint.sh
  docs/docker/integ-test/README.md
  docs/docker/integ-test/images/OpenSearch_Async_API.png
  docs/docker/integ-test/images/integ-test-containers.png
  docs/docker/spark-docker.md
  docs/docker/spark-emr-docker.md
Labels: testing
