Repository opensearch-project/opensearch-spark, pull requests merged in 2025-08, with the labels that each got.

#1239 Add compute platform in Segment name
  flint-core/src/main/java/org/opensearch/flint/core/metrics/reporter/DimensionUtils.java
  spark-sql-application/src/main/scala/org/apache/spark/sql/JobOperator.scala
Labels: backport 0.x, backport 0.7

#1247 fix snapshot uploading
  .github/publish-utils.sh
  .github/workflows/snapshot-publish.yml
Labels: infrastructure

#1256 Switch from AWS OSS sonatype to Maven Central
  .github/publish-utils.sh
  .github/workflows/link-checker.yml
  .github/workflows/snapshot-publish.yml
  .lychee.excludes
  docs/index.md
Labels: infrastructure, backport 0.x

#1122 Add tests with httplogs sample data
  integ-test/src/integration/resources/opensearch/dashboards_sample_data_logs.json
  integ-test/src/integration/resources/opensearch/dashboards_sample_data_logs_mappings.json
  integ-test/src/integration/scala/org/apache/spark/opensearch/table/OpenSearchDashboardITSuite.scala
Labels: DataSource:OpenSearch, stalled, backport 0.x, backport 0.7

#1219 Add precommit for Scala linting
  .pre-commit-config.yaml
  DEVELOPER_GUIDE.md
Labels: infrastructure, stalled
